### ISSUE TITLE
Outputting a list of the cumulative steps per day :question: 

### ISSUE THREAD

**Issue by SiebeA** [cyberjunky/python-garminconnect#100]
Does such a method already exist? Or for now, can the daily steps only be extracted from the `client.get_steps_data` method?

**Comment by dpfrakes** [comment]
I discovered another endpoint that I think addresses this question:

https://github.com/cyberjunky/python-garminconnect/pull/114

**Comment by cyberjunky** [comment]
I just released version 0.1.51

**Comment by SiebeA** [comment]
Great addition @cyberjunky Ron! I've been using it a lot :)

**Comment by SiebeA** [comment]
Great addition @cyberjunky Ron! I've been using it a lot :)
