### ISSUE TITLE
/modern does not work

### ISSUE THREAD

**Issue by andgineer** [cyberjunky/python-garminconnect#102]
If I remove it from URL I am getting good responses.
With '/modern' this is 402

**Comment by cyberjunky** [comment]
For all URL's? Did they change the website perhaps?

**Comment by andgineer** [comment]
https://github.com/cyberjunky/python-garminconnect/pull/103

**Comment by andgineer** [comment]
well I just requested steps

**Comment by andgineer** [comment]
upps that's not that so straightforward - for me it works without /modern for "steps" but to get heart rate infor you do need "/modern/"

**Comment by cyberjunky** [comment]
Do you use the latest code? If i test with the example.py program, option 8 still works for me, weird..
```
8 -- Get steps data for '2022-12-16'
```
Executing: Get steps data for '2022-12-16'

-------------------- api.get_steps_data('2022-12-16') --------------------
[
    {
        "startGMT": "2022-12-15T23:00:00.0",
        "endGMT": "2022-12-15T23:15:00.0",e
        "steps": 0,
        "primaryActivityLevel": "sedentary",
        "activityLevelConstant": true
    },
...
```
Can you try this?

**Comment by andgineer** [comment]
hm and now it really works
But at the morning I got
`Executing: Get steps data for '2022-12-16'

ERROR:__main__:Error occurred: Forbidden url: https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailySummaryChart/MasterAndrey`

**Comment by andgineer** [comment]
Ok close as temporary Garmin's API problems

**Comment by cyberjunky** [comment]
The forbidden url error is annoying, it seems related to the session expired or something, later I will try to add some logic to example file to see if that fixes it.
