### ISSUE TITLE
does not work with python 3.9?

### ISSUE THREAD

**Issue by andgineer** [cyberjunky/python-garminconnect#111]
it works with python 3.11 and python 3.10
but in my conda env with python 3.9 it fails to connect to Garmin:

`  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garminconnect/__init__.py", line 243, in login
    return self.authenticate()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garminconnect/__init__.py", line 363, in authenticate
    response = self.sso_rest_client.post(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garminconnect/__init__.py", line 110, in post
    raise GarminConnectConnectionError(f"Forbidden url: {url}") from err
garminconnect.GarminConnectConnectionError: Forbidden url: https://sso.garmin.com/sso/signin`

**Comment by cyberjunky** [comment]
The forbidden url response sometimes pops up, usually when you do testing, multiple requests or try to access wrong urls. It's some kind of request threshold is triggered (apart from the 427 too many request response)
You can also see this sometimes while using the example.py script, when you then logout (option Z) and log back in, it works again.

**Comment by andgineer** [comment]
Well I know - I saw that too 

But this is something wrong - I try on conda env with python 3.9 - the error
I switch to conda env with python 3.10 - it works
I tried that a number of times

Of cause may be the cause in some other package but I just pip install garminconnect to both conda env, they are both freshly created (no more than two weeks ago)

**Comment by cyberjunky** [comment]
I would like to get the forbidden url issue sorted as a whole, but could not find cause yet.

Can you check the version of these packages on both enviroments?

"requests","cloudscraper"

Also maybe enable debugging especially for requests/urlllib to see what is sent/received...

**Comment by andgineer** [comment]
requests==2.28.1
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
cloudscraper==1.2.66

urllib debug is below(I change my password with ***)

`send: b'GET /sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&webhost=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&privacyStatementUrl=%2F%2Fconnect.garmin.com%2Fen-US%2Fprivacy%2F&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=false&generateNoServiceTicket=false&globalOptInShown=true&globalOptInChecked=false&mobile=false&connectLegalTerms=true&locationPromptShown=true&showPassword=true HTTP/1.1\r\nHost: sso.garmin.com\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nNK: NT\r\nReferer: https://connect.garmin.com/en-US/signin\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Thu, 12 Jan 2023 13:12:30 GMT
header: Content-Type: text/html;charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: CF-Ray: 788624e38c25c259-VIE
header: Access-Control-Allow-Origin: https://www.garmin.com
header: Content-Language: en-US
header: Set-Cookie: org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE=en_US; Path=/
header: CF-Cache-Status: DYNAMIC
header: Access-Control-Allow-Credentials: true
header: Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
header: Access-Control-Allow-Methods: GET,POST,OPTIONS
header: Set-Cookie: SESSION=219f1ddd-7bee-4081-8593-c853e758e1b1; Path=/sso/; Secure; HttpOnly
header: Set-Cookie: __VCAP_ID__=57726d71-a008-48ee-7416-8051; Path=/; HttpOnly; Secure
header: Set-Cookie: __cflb=0H28vqK2vhBdjKAHtwTJuV59urJCcVoo444KgTsTLYc; SameSite=Lax; path=/; expires=Fri, 13-Jan-23 12:12:30 GMT; HttpOnly
header: X-Application-Context: casServer:prod,prod-US_1102,cloud:6
header: X-B3-Traceid: 596343dcad7f1fa40b325f4b43fc0b9f
header: X-Robots-Tag: noindex
header: X-Vcap-Request-Id: 0a85423c-8fba-484d-7b21-7fd9d72b689e
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=7YCpf6xvpoCrBH8l%2B8%2BQEweSnGQzz1Z%2F%2F2NTNihh%2FXxm3cDA2XCPJ07imXztzrUbI7txMb1zhiu8Lgtb9U3bsN6Yuc%2BekmiTZC%2Fj7g6Dp30E9kpau85MaDPQDJ1RD%2BOe"}],"group":"cf-nel","max_age":604800}
header: NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
header: Vary: Accept-Encoding
header: Server: cloudflare
header: Content-Encoding: br
send: b'POST /sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&webhost=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&privacyStatementUrl=%2F%2Fconnect.garmin.com%2Fen-US%2Fprivacy%2F&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=false&generateNoServiceTicket=false&globalOptInShown=true&globalOptInChecked=false&mobile=false&connectLegalTerms=true&locationPromptShown=true&showPassword=true HTTP/1.1\r\nHost: sso.garmin.com\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nAccept-Encoding: gzip, deflate, br\r\nNK: NT\r\nReferer: https://sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&webhost=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&privacyStatementUrl=%2F%2Fconnect.garmin.com%2Fen-US%2Fprivacy%2F&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=false&generateNoServiceTicket=false&globalOptInShown=true&globalOptInChecked=false&mobile=false&connectLegalTerms=true&locationPromptShown=true&showPassword=true\r\nContent-Type: application/x-www-form-urlencoded\r\nCookie: SESSION=219f1ddd-7bee-4081-8593-c853e758e1b1; __VCAP_ID__=57726d71-a008-48ee-7416-8051; __cflb=0H28vqK2vhBdjKAHtwTJuV59urJCcVoo444KgTsTLYc; org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE=en_US\r\nContent-Length: 168\r\n\r\n'
send: b'username=filbert%40yandex.com&password=*****&embed=false&_csrf=B0424E31AEBD776BA5BCA30C1DB731DC6A95B4C935DCF1F3376FAD49A17F717765013B156A33DFA7B3EAD8F4225A31F6FCCA'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Date: Thu, 12 Jan 2023 13:12:30 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: X-Frame-Options: SAMEORIGIN
header: Referrer-Policy: same-origin
header: Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: Expires: Thu, 01 Jan 1970 00:00:01 GMT
header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=wdm6hmHavRjOVmqUUzZYp9d6DgtaVnDwrQt1f7h3W226sjDvX1Y28Me%2FefUTvMe%2B3CO8qoRt5%2BSRhBwFuBHZLKWgb7cwzgzdnCAolsCYKBd21kuKM48ADtHhPhVJ0hMD"}],"group":"cf-nel","max_age":604800}
header: NEL: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
header: Vary: Accept-Encoding
header: Server: cloudflare
header: CF-RAY: 788624e5bff8c259-VIE
header: Content-Encoding: br`

**Comment by cyberjunky** [comment]
Do you see differences in package versions between the two environments, and significant change in debug output?

I remove the output because of possible token info.

**Comment by andgineer** [comment]
ok thank you - I thought the token is temp thing

well in good environment this is

cloudscraper==1.2.66
requests==2.28.1
requests-oauthlib==1.3.1
requests-toolbelt==0.10.1
types-requests==2.28.11.7

exactly the same
may be some difference in certs packagers but at least certs also the same

**Comment by andgineer** [comment]
I compared urlib debugs
Of cause a lot of differences - different sessions, csrf etc

but some strange header if the FAILED request that I do not see in good one

header: X-Frame-Options: SAMEORIGIN
header: Referrer-Policy: same-origin

**Comment by cyberjunky** [comment]
These last ones are probably the result of a proper login, but not the cause.
cloudscraper has newer version, but only typo fixes. And I can image the other package behave differently between Python verions, but of course this can be the case.
What about things like date/time settings on the 3.9 hosts, mabe off by hours having the cert failed?

**Comment by andgineer** [comment]
No more I can reproduce that
