### ISSUE TITLE
Forbidden url: https://sso.garmin.com/sso/signin

### ISSUE THREAD

**Issue by demokedes** [cyberjunky/python-garminconnect#113]
Dear all,
I am using this script. It is amazing. From the beginning it was working very nicely. 
Than I modified it a bit in a way, every week I get HR data for the last week and import it into my own database.
The problem arises, because sometimes, not always I get following error. 
`__init__.py", line 110, in post
    raise GarminConnectConnectionError(f"Forbidden url: {url}") from err
garminconnect.GarminConnectConnectionError: Forbidden url: https://sso.garmin.com/sso/signin
`
I have a feeling it has to do something with Cloudflare that my ip is blocked. 
Any idea how to overcome this? Can I shomehow whitelist my IP? I am all the time connecting from the same IP.
Thank you in advance!

**Comment by cyberjunky** [comment]
@demokedes This is a long standing issue, which pops up every now and then, specially with new login, or frequent tries/testing...Cause it not yet known, I still need to fix some error catching as stated in other issue, but don't think this fixed it.
When you run into it using the example.py code, a simple logout/login fixes it, so creating new cookies and tokens.
Will need some more investigation..

**Comment by pzelnip** [comment]
I was getting this error today, seemed to persist for about 10 minutes & then started working fine (no change to code, no logging out, etc, just rerunning the [same script](https://github.com/pzelnip/garmin/blob/main/garmin.py#L119) I had before). 🤷 

FWIW the last failing stacktrace I got was:

```
Traceback (most recent call last):
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 99, in post
    response.raise_for_status()
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&webhost=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&privacyStatementUrl=%2F%2Fconnect.garmin.com%2Fen-US%2Fprivacy%2F&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=false&generateNoServiceTicket=false&globalOptInShown=true&globalOptInChecked=false&mobile=false&connectLegalTerms=true&locationPromptShown=true&showPassword=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/adamparkin/temp/sandbox/garmin/garmin.py", line 188, in <module>
    exit(main())
  File "/Users/adamparkin/temp/sandbox/garmin/garmin.py", line 179, in main
    result = process_range(start_date, days)
  File "/Users/adamparkin/temp/sandbox/garmin/garmin.py", line 159, in process_range
    with garmin_api():
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/Users/adamparkin/temp/sandbox/garmin/garmin.py", line 133, in garmin_api
    initialize_api()
  File "/Users/adamparkin/temp/sandbox/garmin/garmin.py", line 124, in initialize_api
    if not API.login():
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 256, in login
    return self.authenticate()
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 376, in authenticate
    response = self.sso_rest_client.post(
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 109, in post
    raise GarminConnectConnectionError(f"Forbidden url: {url}") from err
garminconnect.GarminConnectConnectionError: Forbidden url: https://sso.garmin.com/sso/signin
```

**Comment by pzelnip** [comment]
Encountered this *several* times this morning.  Replicated with this script:

```
from datetime import date
import os
from garminconnect import Garmin

API = Garmin(os.getenv("GARMIN_EMAIL"), os.getenv("GARMIN_PASSWORD"))
if API.login():
    day = date(2023, 2, 18)
    print(API.get_daily_steps(day, day))
```

With that, I ran it around 10-15 times, and was only successful twice.  Example failing trace:

```
Traceback (most recent call last):
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 99, in post
    response.raise_for_status()
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&webhost=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&privacyStatementUrl=%2F%2Fconnect.garmin.com%2Fen-US%2Fprivacy%2F&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=false&generateNoServiceTicket=false&globalOptInShown=true&globalOptInChecked=false&mobile=false&connectLegalTerms=true&locationPromptShown=true&showPassword=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/adamparkin/temp/sandbox/garmin/sso.py", line 6, in <module>
    if API.login():
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 256, in login
    return self.authenticate()
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 376, in authenticate
    response = self.sso_rest_client.post(
  File "/Users/adamparkin/.envs/garmin/lib/python3.9/site-packages/garminconnect/__init__.py", line 107, in post
    raise GarminConnectAuthenticationError("Authentication error") from err
garminconnect.GarminConnectAuthenticationError: Authentication error
```

**Comment by fm-sys** [comment]
Just want to mention that I have the same issue. Login via `session.json` only works for a few minutes, afterwards a new login is necessary.

**Comment by pzelnip** [comment]
So I think I fixed the issue for my scenario.  I noticed that I only ran into this issue on one of my machines, and in fact on that machine it happened *often* (ie more times than not).

On my other machine (both are M1 Macbooks), never once ran into this SSO issue.  So that led me to wondering "what's different about the two?" and turned out, quite a bit in terms of the Python environment being used.

On the working machine, I had Python installed and managed through Pyenv.  I was running Python 3.10.4.

On the troublesome machine, I had Python installed through homebrew, and was running Python 3.9.16.  

Both were using virtual environments created through [virtualenv](https://virtualenv.pypa.io/en/latest/)

Today I changed the problematic machine to run/manage Python through Pyenv as well, and switched to Python 3.10.9 and have had no SSO issues since.

So there's two potential causes in my case I can think of:

* the homebrew supplied Python was messed up
* there's something in Python 3.9 that messes up compared to 3.10

I then installed Python 3.9.16 through pyenv, created a virtual env with that version, installed all the dependencies I had, and tried running the short script in my message above.  It worked 3 times in a row, and then on the 4th I got the same SSO error.  So seems like something in Python 3.9 that's causing troubles. 🤷

**Comment by jrast** [comment]
> Just want to mention that I have the same issue. Login via `session.json` only works for a few minutes, afterwards a new login is necessary.

I can confirm this. I'm working with python 3.10, so the issue is not only present when python 3.9 is in use as mentioned by @pzelnip

**Comment by app4g** [comment]
I can't get pass login :-( 
I tried 3.9 and 3.11 version of python

**Comment by prog-dude** [comment]
I frequently get this error my self. I don't think Garmin likes projects like this, and are trying to hinder them in working. For a while I had written something myself using selenium, but lately that stopped working more and more often. (I run it daily and adds the data to a spreadsheet where I can organize the data as I want it.)
I don't have any ideas on how to fix it, but thinks it boils to Garmin not liking us...

**Comment by dan-p-p** [comment]
Hi all, 

I've had the same issue when using a different library: https://github.com/petergardfjall/garminexport. Users of that library also reported that (too many/too frequent) logins resulted in the errors described above. In my experience, for debugging/DEV purposes using a VPN and making the calls from a different IP address resolved the issue. So yes, it seemed Cloudflare related like the OP suggests. 

Then the logins stopped working entirely. 

However, using a fix to that package with a mod to deal with the Cloudflare issue, solved this for me. I specifically use this package: garminexport[cloudflare]

Hope this helps!

**Comment by cyberjunky** [comment]
@dan-p-p Hi Dan, can you point me to the mod/code you mentioned? This issue is there for a long time, and yes more often if you access the data more often, would like to solve it, or make it less prone to account disable... thanks!

**Comment by dan-p-p** [comment]
Hi @cyberjunky , 

I followed this thread, which I see also refers to one of your posts: https://github.com/petergardfjall/garminexport/pull/92. Note I am using Pete Gardfjall's Garmin Export library to download/read Garmin files. Installed that with the option Cloudflare: pip install garminexport[cloudflare] and that solved it.

**Comment by lakemike** [comment]
Maybe helpful. I am using Macos and I get different behaviour depending on x86_64 (i386) or amd64 architecture of python being used.
x86_64 => no problems
amd64 => crashes almost every time with the SSO error mentioned above

**Comment by rotweintrinker** [comment]
I just had this message, when I stayed at my mother it doesn't work, when I used my 4G card it also not works, now I'm back home and it works again.
No changes, no restart, maybe they are looking for the IP or other parts of the connection.
Hope that helps.

**Comment by rotweintrinker** [comment]
I now cross checked it at home.
First I connected by WAN, it doesn't work, then I disconnected the WAN and connected by WLAN and it works.
Any Idea for the reason?

**Comment by cyberjunky** [comment]
@rotweintrinker @lakemike @dan-p-p  and others, can you test with version 0.2.3 and let me know if this solved the issue, I haven't had any error while developing/testing, and I tested a lot.

**Comment by rotweintrinker** [comment]
> @rotweintrinker @lakemike @dan-p-p and others, can you test with version 0.2.3 and let me know if this solved the issue, I haven't had any error while developing/testing, and I tested a lot.
@cyberjunky 
Hi Ron,
I now upgraded to Python 3.11 and so I was able to check it.
It works now in my wlan and I'm able to disconnect and connect the wan. And I can also connect to Garmin.
Next Week I will stay again at my Mother, then I wich check it again.
Grat Work!

**Comment by matin** [comment]
This can be closed. Garth solved this issue.
