### ISSUE TITLE
Question: Support for MFA

### ISSUE THREAD

**Issue by philosowaffle** [cyberjunky/python-garminconnect#122]
Hello 👋, I work on a related tool [peloton-to-garmin](https://github.com/philosowaffle/peloton-to-garmin).  I don't consume this library directly, but have referenced the code before to compare notes and _discover_ Connect API endpoints.

With the recent announcement of the [ECG App](https://www.garmin.com/en-US/garmin-technology/health-science/ecg/) I have a [handful of users](https://github.com/philosowaffle/peloton-to-garmin/discussions/408) who are taking advantage of this. However, it seems that in order to take advantage of this new feature, Garmin requires the user enable multi-factor authentication for obvious security reasons.

I've begun researching [implementing MFA support](https://github.com/philosowaffle/peloton-to-garmin/issues/410) on my end, but have hit a bit of a wall at the very last step (after successfully validating the user provided MFA code).

I was curious if this was something already on the radar for this project or if y'all have made any progress on supporting MFA?

**Comment by philosowaffle** [comment]
Turns out what I had was working just fine. Garmin/Cloudflare had just temporarily blocked my account.  If y'all ever add support for this, I have the general flow documented on my ticket for reference.

**Comment by cyberjunky** [comment]
@philosowaffle Great I will have a look, thanks!

**Comment by nelbs** [comment]
> @philosowaffle Great I will have a look, thanks!

Hopefully you can implement 2FA since I cannot use this component anymore after I enabled the ECG app.
