### ISSUE TITLE
Login rate limit

### ISSUE THREAD

**Issue by BernieV1977** [cyberjunky/python-garminconnect#127]
Hello, 
What is the login rate limit before being blocked by Garmin?

**Comment by cyberjunky** [comment]
It's unknown (to me at least)

**Comment by NicKarlen** [comment]
It is not that high... Don't know how many times I logged in but i just hit the Limit.

**Comment by NicKarlen** [comment]
The answer is yes. Garmin undoes the API-call-limit-blockage after about 1 hour

**Comment by cyberjunky** [comment]
Can you test latest version, it should work fine now!
