### ISSUE TITLE
Blood pressure data

### ISSUE THREAD

**Issue by ajgraven** [cyberjunky/python-garminconnect#128]
It doesn't look like its possible to pull blood pressure data from Garmin. Is it possible to add this feature, or does Garmin's API not support pulling BP info?

**Comment by cyberjunky** [comment]
Is this data available on the garmin connect website? If so, there is a possibility, if not then we cannot do this currently.

**Comment by cyberjunky** [comment]
Closed because of stale ticket, please (re)open if needed, request was implemented.
