### ISSUE TITLE
Is 2FA taken into consideration ?

### ISSUE THREAD

**Issue by dr400** [cyberjunky/python-garminconnect#129]
I'm asking and interested to know how you deal with 2FA.

On the other hand i'm encoutering this error : 

Executing: Get activity data for '2023-03-07'

ERROR:__main__:Error occurred: Forbidden url: https://connect.garmin.com/modern/proxy/usersummary-service/usersummary/daily/None

and

ERROR:garminconnect:Login ticket not found (200).

session.json is giving : null

Thanks for your help

**Comment by matin** [comment]
This can be closed. Garth includes MFA.
