### ISSUE TITLE
Batch download of a certain activity

### ISSUE THREAD

**Issue by arozans** [cyberjunky/python-garminconnect#131]
I know there is a method to download a sleep for a specific date. How about date ranges? Is it possible to query only one time and get sleep data for multiple days rather than query each day separately and risk HTTP 429 Too Many Requests?

**Comment by matin** [comment]
@arozans I'm currently fetching three years of sleep data with ten threads, and I've never run into issues like receiving a 429. Please make sure you're using version 0.2, and you shouldn't run into any issues.

**Comment by cyberjunky** [comment]
@arozans Is this still an issue with latest versions?

**Comment by arozans** [comment]
Let's close it for now, hasn't happened to me lately.
