### ISSUE TITLE
adding Garmin Connect Women’s Health API features?

### ISSUE THREAD

**Issue by Mmmarjan** [cyberjunky/python-garminconnect#134]
Hello,
I really like this project!

Is it possible to add Garmin Connect Women’s Health API features like Menstrual Cycle Tracking?
It's not possible to download it manually from Garmin Connect. I would like to analyze this data over time, for example combined with heart rate.

Thanks in advance!
Kind regards
Marjan

**Comment by psdupvi** [comment]
Full disclosure: I'm a male, so I have limited experience with this, and my wife does not use Garmin.

That said, I created a bare bones profile for her and we'll track some period data in Garmin Connect to see if we can find any endpoints.

There are a few settings you have to choose before you set it up, related to your period, your contraceptives, and some things to track

![image](https://github.com/cyberjunky/python-garminconnect/assets/17414247/403d66f4-f201-4697-8dd3-c33026761f9c)

It looks like these are accessible via the User Settings endpoint that already exists, under the key `userMenstrualCycleSettings`

Then, I've found one menstrual health endpoint so far, `https://connect.garmin.com/periodichealth-service/menstrualcycle/dayview/2024-03-11?todayDate=2024-03-11`, which returns the following data (I just randomly selected some of the options available in the daily log, see image at the end):


```json
{
    "daySummary": {
        "startDate": "2024-02-25",
        "dayInCycle": 16,
        "periodLength": 5,
        "currentPhase": 3,
        "lengthOfCurrentPhase": 7,
        "daysUntilNextPhase": 2,
        "fertileWindowStart": 11,
        "lengthOfFertileWindow": 7,
        "predictedCycleLength": 28,
        "educationContentMod": 0,
        "cycleType": "REGULAR",
        "predictedCycle": false
    },
    "dayLog": {
        "userProfilePk": 120846682,
        "calendarDate": "2024-03-11",
        "symptoms": [
            "BACKACHE",
            "FATIGUE"
        ],
        "moods": [
            "HAPPY",
            "ENERGETIC"
        ],
        "discharge": [
            "CREAMY"
        ],
        "flow": null,
        "sexDrive": "AVERAGE",
        "sexualActivity": "PROTECTED",
        "notes": null,
        "reportTimestamp": "2024-03-12T00:53:08.548",
        "hasBabyMovement": false,
        "ovulationDay": false
    }
}
```

I'm guessing this endpoint will provide the bulk of the data around here.  I do wonder how pregnancy, unusual/no periods, and other things will play into this.

I'll look at adding this and a few others after I've tested some menstrual data through my wife.  


Daily Log Options:
![image](https://github.com/cyberjunky/python-garminconnect/assets/17414247/c29e2ed4-0562-4f01-b24e-288dc8ce5f4f)

**Comment by cyberjunky** [comment]
@Mmmarjan if there is still interest in this I added the code from @psdupvi to version 0.2.14, can you check?

**Comment by Mmmarjan** [comment]
Yes, this is really helpful! Thanks a lot. I tested the 2 endpoints for menstrual data. I could not test the pregnancy summary, it returns no data (as I'm not using that feature).

**Comment by cyberjunky** [comment]
@Mmmarjan thanks, closing, if you need any help or other features you are free to create an issue ofcourse!
