### ISSUE TITLE
HRV data api.get_hrv_data JSON error

### ISSUE THREAD

**Issue by benninkcorien** [cyberjunky/python-garminconnect#137]
Thank you for this!

Works wonderfully for api.get_stats and api.get_stats_and_body but `api.get_hrv_data` errors out for me with what looks like incorrectly formatted JSON or something?

     display_json(f"api.get_hrv_data({today.isoformat()})", api.get_hrv_data(today.isoformat()))
     File "F:\Garmin\venv\lib\site-packages\garminconnect\__init__.py", line 653, in get_hrv_data
     return self.modern_rest_client.get(url).json()
     File "F:\Garmin\venv\lib\site-packages\requests\models.py", line 975, in json
     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
     requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by matin** [comment]
@benninkcorien can you the version with the [Garth migration](https://github.com/matin/python-garminconnect/tree/garth) to see if it fixes the problem?

I just added [a test for it](https://github.com/cyberjunky/python-garminconnect/pull/144/commits/7ceeb97ad38ad9dc1b8078d0152a9e6499b0d83f)

**Comment by benninkcorien** [comment]
@matin Thanks! 

Is that `pip install git+https://github.com/matin/python-garminconnect.git` ?

I'm still getting the same error, but I'm not sure if I installed the correct version..

**Comment by matin** [comment]
@benninkcorien you need to install the `garth` branch. Can you try the following instead?

```bash
pip install git+https://github.com/matin/python-garminconnect.git@garth#egg=garminconnect
```

**Comment by benninkcorien** [comment]
Got a log in error using the script I used with the other garminconnect version, so I started over following your documentation.

I'm getting full results for DailySteps and Stress,  but an empty array for HRV and Sleep.

    [DailySteps(calendar_date=datetime.date(2023, 8, 13), total_steps=1430, total_distance=1082, step_goal=2000), 
    DailySteps(calendar_date=datetime.date(2023, 8, 14), total_steps=2285, total_distance=1728, step_goal=2000)]
    [{'calendarDate': '2022-08-07', 'value': 27}, {'calendarDate': '2022-08-14', 'value': 28}]


Sleep code is

    sleep = garth.DailySleep.list("2023-08-23", 12)
    print(f"SLEEP, \n {sleep}") 
    
    SLEEP,
     []

(and sleepdata for a week `sleepweek = garth.SleepData.get(end="2023-08-20", days=10)` errored with `unexpexted keyword 'end' `

**Comment by matin** [comment]
@benninkcorien try running this Colab:
https://colab.research.google.com/gist/matin/8fe7ec074cbb91a689c12ab81bf74f4e/daily_sleep_and_hrv.ipynb

<img width="329" alt="image" src="https://github.com/cyberjunky/python-garminconnect/assets/98985/8d56e45e-c88b-4bb5-bd01-904b51b512a9">

I used the same date and period as you.

**Comment by matin** [comment]
> (and sleepdata for a week `sleepweek = garth.SleepData.get(end="2023-08-20", days=10)` errored with `unexpexted keyword 'end' `

You're using `SleepData.get()` where you should be using `SleepData.list()`. Try the following:
```python
garth.SleepData.list(end="2023-08-20", days=10)
```

`SleepData` provides extremely detailed daily sleep data (including your sleep stages, movements, etc. It's helpful to produce these kinds of graphs:
![image](https://github.com/cyberjunky/python-garminconnect/assets/98985/b5a6b54f-85e5-4bd8-8c68-68c75af24c2c)

![image](https://github.com/cyberjunky/python-garminconnect/assets/98985/17374372-205c-4438-83c3-58e9b5fb2c0b)

There's no weekly sleep data, but you could certainly calculate it by averaging the daily numbers. You could use Pandas to calculate a rolling average like this: [28-day rolling average of stress](https://colab.research.google.com/github/matin/garth/blob/main/colabs/stress.ipynb).

**Comment by cyberjunky** [comment]
Closing, since we merged Garth into garminconnect, and added some new calls, if you miss anything let me know
