### ISSUE TITLE
Unknown error occured during Garmin Connect Client login

### ISSUE THREAD

**Issue by donpablos** [cyberjunky/python-garminconnect#14]
DEBUG:garminconnect:Login to Garmin Connect using POST url https://sso.garmin.com/sso/signin
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sso.garmin.com:443
Unknown error occured during Garmin Connect Client login

As well I can't login via browser https://sso.garmin.com/sso/signin. Login via browser to 
https://connect.garmin.com/modern/ work perfect

![garminJPG](https://user-images.githubusercontent.com/6905185/84242522-3cb47d80-ab01-11ea-9c48-3aa530d1b824.JPG)

**Comment by cyberjunky** [comment]
I don't think login to via browser https://sso.garmin.com/sso/signin is supported.
Are you using this library in home-assistant or with your own project?
If the last option can you try version 0.1.14? Hopefully this will give better error feedback.

**Comment by donpablos** [comment]
Thanks for your a quick anserw. I installed a new version of garminconnect and received the same log:

garminconnect version: 0.1.14
DEBUG:garminconnect:Login to Garmin Connect using POST url https://sso.garmin.com/sso/signin
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sso.garmin.com:443
Unknown error occured during Garmin Connect Client login

I only add this modification to your example program from README.md:
import garminconnect as gr
print(f"garminconnect version: {gr.__version__}")
YOUR_EMAIL="donpablos@o2.pl"
YOUR_PASSWORD="XXXX"

**Comment by donpablos** [comment]
1) Yes, I executed  this code and received the same issue. 
2)  Finally I solved the problem 

I executed  this code 

https://github.com/benniblau/GarminConnectActivityExport/blob/master/GarminConnectActivityExport.py

and received more precise information:

Requests (Caused by SSLError(“Can't connect to HTTPS URL because the SSL module is not available.”) 


after installation OpenSSL everything work
https://github.com/conda/conda/issues/8046#issuecomment-450515815

big THANKS for your help :)

**Comment by st20m010** [comment]
eeey still no work
