### ISSUE TITLE
requires-python may be too strict

### ISSUE THREAD

**Issue by frostming** [cyberjunky/python-garminconnect#150]
The latest version on PyPI requires python >=3.10. I wonder if it is a mistake or intended, since otherwise users on older python versions are not able to use the version and will fallback to a problematic version 0.2.1, which I suggest should be yanked.

P.S. PDM author here.

**Comment by cyberjunky** [comment]
@frostming you are absolutely right, I had put some time in it last evening to get it working together with my Garmin Connect Home Assistant integration and it kept failing to install, had it removed and it worked. Problably put a less stricter one back later. Thanks for the heads up, and for PDM I used it for the first time after seeing @matin using it for his project. I just released 0.2.3.
