### ISSUE TITLE
Can not install package with pip

### ISSUE THREAD

**Issue by thanhnam007** [cyberjunky/python-garminconnect#159]
Can you help me check this error, after i run this command: `pip3 install garminconnect`:

`Collecting garminconnect
  Obtaining dependency information for garminconnect from https://files.pythonhosted.org/packages/ae/33/05cfb344ffccffaf0559383b75d01deb155fbc5c823f537d37645aa0d524/garminconnect-0.2.7-py2.py3-none-any.whl.metadata
  Using cached garminconnect-0.2.7-py2.py3-none-any.whl.metadata (3.1 kB)                                                                                                                                             
INFO: pip is looking at multiple versions of garminconnect to determine which version is compatible with other requirements. This could take a while.
  Obtaining dependency information for garminconnect from https://files.pythonhosted.org/packages/6d/50/6d246da39d59270c15c97f61f0ca0af33b2cdc37408060e40e98b2474775/garminconnect-0.2.6-py2.py3-none-any.whl.metadata
  Using cached garminconnect-0.2.6-py2.py3-none-any.whl.metadata (2.9 kB)                                                                                                                                             
  Obtaining dependency information for garminconnect from https://files.pythonhosted.org/packages/e9/83/36f1f3185bcf990a878cb938e8ff71654c826a3be3a7490135b00b58f48e/garminconnect-0.2.5-py2.py3-none-any.whl.metadata
  Using cached garminconnect-0.2.5-py2.py3-none-any.whl.metadata (2.9 kB)                                                                                                                                             
  Obtaining dependency information for garminconnect from https://files.pythonhosted.org/packages/a5/8d/19a428986a85867d4027fef7a18830df2ef4e60eb8ed24dc55e2f64677e3/garminconnect-0.2.4-py2.py3-none-any.whl.metadata
  Using cached garminconnect-0.2.4-py2.py3-none-any.whl.metadata (2.9 kB)
  Obtaining dependency information for garminconnect from https://files.pythonhosted.org/packages/3e/fb/4bd3a13d42132f81192c86de6dcbd66f548122c24499a4a6929cd3cc6c19/garminconnect-0.2.3-py2.py3-none-any.whl.metadata
  Using cached garminconnect-0.2.3-py2.py3-none-any.whl.metadata (2.7 kB)
  Using cached garminconnect-0.2.1.tar.gz (21 kB)
ERROR: garminconnect from https://files.pythonhosted.org/packages/90/0d/f09b135a5de0599e2911f42068532ff7191e9d9cc1423956ed43d7bfb21a/garminconnect-0.2.1.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyprojec
t.toml' found.`

**Comment by matin** [comment]
What version of Python are you using?

**Comment by cyberjunky** [comment]
@thanhnam007 kindly reminder...

**Comment by cyberjunky** [comment]
If you still have this issue, please (re)open an issue, closing for now..
