### ISSUE TITLE
activities have empty splitSummaries arrays even when lapCount>1

### ISSUE THREAD

**Issue by Beans0nT0ast** [cyberjunky/python-garminconnect#16]
I'm trying to extract lap times and related data from a run activity. 
After extracting an activity list for a run using get_activities which has lapCount>1, I find hasSplits = False and splitSummaries = [].

Has something gone wrong, or are these fields something distinct from lap data?

**Comment by michaeldeaton** [comment]
You should be able to use the CSV download that just got merged in, it has splits in it iirc..

https://github.com/cyberjunky/python-garminconnect/pull/19

**Comment by cyberjunky** [comment]
I just release version 0.1.16 with this code, thanks all!
