### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by andgineer** [cyberjunky/python-garminconnect#164]
With the same code that worked before

    api = Garmin(email, password)
    api.login()

interactive login with this password works

latest version 
garminconnect               0.2.8

error
garminconnect/__init__.py", line 382, in authenticate
    self.display_name = user_prefs["displayName"]

**Comment by andgineer** [comment]
hm do not understand that - all 200 in the cassette
https://github.com/andgineer/garth/blob/main/tests/cassettes/test_login_success.yaml

**Comment by cyberjunky** [comment]
Did it work before on version 0.2.x? I saw some people reporting similar issues in my Home Assistant integration https://github.com/cyberjunky/home-assistant-garmin_connect, could it be a Garmin service down issue? People on Reddit reported some issues with app as well..

**Comment by cyberjunky** [comment]
Have this issue myself as well on my dev Blue, will investigate

**Comment by andgineer** [comment]
I got it on 0.1.50 and upgraded to the latest thinking it will help

**Comment by cyberjunky** [comment]
> I got it on 0.1.50 and upgraded to the latest thinking it will help

That is strange, because 0.2.x versions use a completely new way of fetching data from Garmin, do you have Garmin app working fine, and do you have MFA enabled by any chance?

**Comment by andgineer** [comment]
I do not know what is Garmin app.
Garmin Connect site and my Garmin watch works fine, no MFA

debugging the lib I see that
params = {"ticket": found.group(1)} # there is some ticket code
response = self.modern_rest_client.get("", params=params)

do not return VIEWER_USERPREFERENCES but some very strange page with a lot of js

**Comment by andgineer** [comment]
oops
I am very sorry
I mixed my venvs and used the one with 0.1.50 version

With the latest version it works
