### ISSUE TITLE
Change the activity name

### ISSUE THREAD

**Issue by polcar** [cyberjunky/python-garminconnect#172]
Hi,

I try to extend API to modify the name of an activity:

```
url = f"{self.garmin_connect_activity}/{activity_id}"
payload = {"activityId": activity_id, "activityName": title}
return self.garth.post("connect", url, json=payload)
```

I must add `x-http-method-override: PUT` to `headers` to avoid 400 as HTTP status code. But now I am endig with:
```
ERROR:__main__:Error in request: 401 Client Error: Unauthorized for url: https://connect.garmin.com/activity-service/activity/<ACTIVITY_ID>
```

When I use the  Bearer token from Chrome session in `authorization` header, I am able to change an activity name. It looks like the authentication must me improved, I am correct?

**Comment by matin** [comment]
Garth already has a [PUT method](https://github.com/matin/garth/blob/main/garth/http.py#L144).

You should be doing the following:

```python
self.garth.put("connectapi", url, json=payload, api=True)
```

There's an example in the tests to [update heart rate zones](https://github.com/matin/garth/blob/69a1fd4bfa2a697e15e15661eae60f6d9541daf2/tests/test_http.py#L187-L210).

HTH

**Comment by polcar** [comment]
It works. Thanke you very much.

**Comment by cyberjunky** [comment]
@polcar I will add this to new version as set_activity_name(id, name)
