### ISSUE TITLE
Pulling HR data for multiple days

### ISSUE THREAD

**Issue by demokedes** [cyberjunky/python-garminconnect#176]
Dear cyberjunky,
I am using this repo for a while. In the last days, I upgraded to newer version with Gart. In general I like it, because there are no more issued with authorization. I can get normally daily HR data. If I try to get data for multiple days (through for loop), I can not get it. I get following error.
The same logics was working before gart. Any ide what might be the reason?
`WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='connectapi.garmin.com', port=443): Read timed out. (read timeout=10)")': /wellness-service/wellness/dailyHeartRate/demokedes?date=2023-11-15`

**Comment by matin** [comment]
Is it failing?

That's a warning message stating that there was a timeout and is automatically retrying.

**Comment by cyberjunky** [comment]
@demokedes Closing because it has become stale, please (re)open a issue if this is still happening.
