### ISSUE TITLE
download_activity format

### ISSUE THREAD

**Issue by Keenpachi** [cyberjunky/python-garminconnect#179]
How to define value for parameter dl_fmt of method download_activity to get response as CSV?

below attempts are not working:

garmin.download_activity(activity_id, dl_fmt="CSV") 
garmin.download_activity(activity_id, dl_fmt=garminconnect.Garmin.ActivityUploadFormat.CSV)

**Comment by theboywho** [comment]
based on example.py:
https://github.com/cyberjunky/python-garminconnect/blob/0472785ccea22938170c3098feb59a7d38a4066b/example.py#L385

Something like this should work:
```python
garmin.download_activity(activity_id, dl_fmt=garmin.ActivityDownloadFormat.CSV)
```

**Comment by Keenpachi** [comment]
Yep thank you. I mixed up the method names. Now is working fine.
