### ISSUE TITLE
Download the .csv file

### ISSUE THREAD

**Issue by albertoivo** [cyberjunky/python-garminconnect#18]
I saw that this code can download .tcx, .gpx. 

I would like to know if it can download .csv files

Thanks in advance.

**Comment by albertoivo** [comment]
Hi,

I kind of figure it out just adding this line in `download_activity`:

```python
Garmin.ActivityDownloadFormat.CSV: f"{self.url_csv_download}{activity_id}"
```

where `url_csv_download` is:
```python
url_csv_download = MODERN_URL + "/proxy/download-service/export/csv/activity/"
```

It downloads a .csv file as expected. The problem is the format of the file. It downloads as all the activities is **running**, but actually they're `rowing`. The columns are pretty different.

When I download the .csv file direct from Garmin Connect, it's correct.

Can anyone help me on this?

Thanks in advance!

**Comment by kbamps** [comment]
Hi Alberto,

Did you manage to download the .csv file?  If yes, would you be so kind to share you solution?

Thanks in advance!

**Comment by michaeldeaton** [comment]
Hi @kbamps / @albertoivo - CSV support just got merged in..

https://github.com/cyberjunky/python-garminconnect/pull/19

**Comment by cyberjunky** [comment]
I haven't created a new version on pypi yet, will do tomorrow.

**Comment by cyberjunky** [comment]
I just release 0.1.16 with this code, thanks all.
