### ISSUE TITLE
New methods: get and delete activity by id

### ISSUE THREAD

**Issue by lrybak** [cyberjunky/python-garminconnect#187]
Hi Ron, thank you for the very useful software. I would like to ask if it would be possible to add a method that allows:
- retrieving an activity by its ID
- deleting an activity by its ID

Garmin is not counting my zwift indoor rides to badges trophies and I writing myself kind of script to convert that rides to "garmin virtual rides". Above methods would help me with that.

**Comment by thienlamc** [comment]
butailijie

**Comment by psdupvi** [comment]
I can take a look at this if no one else has

**Comment by psdupvi** [comment]
It looks like the function currently called `get_activity_evaluation` , which accepts an activity id, actually returns the full activity summary JSON.  Also, separately, `download_activity` accepts the activity ID and the format you'd like to download, and downloads the file for you.

I'll create a PR to rename `get_activity_evaluation` to `get_activity`, but in the meantime you can use that to retrieve activites by ID

Separately, I'll work on an activity deletion endpoint

**Comment by cyberjunky** [comment]
@lrybak I added the code from @psdupvi to version 0.2.14, can you check?

**Comment by cyberjunky** [comment]
A bit stale, so closing, if still an issue please (re)open one!
