### ISSUE TITLE
Error when trying to upload the weight

### ISSUE THREAD

**Issue by Gogmaghog** [cyberjunky/python-garminconnect#196]
Hi!!

Does anyone else get an error when trying to upload weight?

Executing: Add a weigh-in of 89.6kg on '2024-03-31'

ERROR:__main__:Error in request: 400 Client Error: Bad Request for url: https://connectapi.garmin.com/weight-service/user-weight

**Comment by psdupvi** [comment]
It looks like Garmin might have changed the names of the times, from `measurementTimestampLocal` and `measurementTimestampGMT`  to `dateTimestamp` and `gmtTimestamp`

**Comment by cyberjunky** [comment]
Fixed in 0.2.16, thanks to @psdupvi
