### ISSUE TITLE
Session Timeout?

### ISSUE THREAD

**Issue by psilo909** [cyberjunky/python-garminconnect#2]
Hi, 

I created a plugin for our smarthome software SmartHomeNG using your library.

It appears that there is a session timeout.

I only once called client = garminconnect.Garmin(YOUR_EMAIL, YOUR_PASSWORD), but this morning I got an empty dict back.
After restart of our software, it is working again. I now added client = garminconnect.Garmin(YOUR_EMAIL, YOUR_PASSWORD) before each call, which now makes the request duration much longer (suppose login each time).

Is there any way to check if there is still a valid session, so that i can avoid a relogin each time?

Bye,
René

**Comment by cyberjunky** [comment]
I guess we can check for empty dict or other non-valid response inside the fetch_* routines and call login if needed, at which interval do you poll?

**Comment by psilo909** [comment]
currently i dont poll in an intervall at all.. just integrated your functions in a webinterface of my plugin and they are called once i open the webpage. as our software is running continously, the interval can therefore get "days".. the interval once i encountered the problem was "1 night" (stopped yesterday around 19:00 and opened the webif today at around 7-8)

but even without polling it should be able to care for these timeouts.. i also thought about checking for the empty dict.. but i am not sure which value is save to check. sometimes values can just be empty because i did not sync my watch for that day. which field would you propose?

**Comment by psilo909** [comment]
by the way: i just was outside for about 1 hour, and again i'am having a timeout:

 requests.exceptions.HTTPError:  403  Client  Error:  Forbidden  for  url:  https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailyHeartRate/...

**Comment by psilo909** [comment]
if its ok i will directly integrate your code into my plugin and not use the pypi package anymore. in case i find a good solution for the timouts i can hand over the code...

from an MIT license point of view, this should be ok, right? i will mention you and your library.

**Comment by cyberjunky** [comment]
I have done a test and what I see is when the session is expired, the returned JSON data contains the field displayName whereas before it wasn't included and field: 'privacyProtected'= True, instead of False, rest of the field contain the value None.

So we can use privacyProtected value to detect we need to login again.
Will have a look.

**Comment by psilo909** [comment]
that only counts for the stats. if you request the heart rates, you run into a 403. i put in a little bit exception handling around your requests and get a:

Exception occured during stats retrieval: 403 Client Error: Forbidden for url: https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailyHeartRate/xxx?date=2020-01-07

**Comment by cyberjunky** [comment]
Didn't test that one, correct, made a module with logging entries.
Exception handling can be implemented better...true

**Comment by psilo909** [comment]
my current code.. not sure if this works:

```
    def _fetch_stats(self, cdate):  # cDate = 'YYY-mm-dd'
        """
        Fetch available activity data
        """
        getURL = self.url_activities + self.display_name + '?' + 'calendarDate=' + cdate

        try:
            response = self._session.get(getURL, headers=self.headers)
            response.raise_for_status()
        except requests.exceptions.HTTPError as e:
            self.logger.error("Exception occured during stats retrieval: %s" % e)
            return
        if response['privacyProtected'] is True:
            self.logger.info(
                "Session expired - trying relogin: %s" % e)
            self._login(self._email, self._password)
            try:
                response = self._session.get(getURL, headers=self.headers)
                response.raise_for_status()
            except requests.exceptions.HTTPError as e:
                self.logger.error("Exception occured during stats retrieval: %s" % e)
                return
        return response.json()

    def _fetch_heart_rates(self, cdate):  # cDate = 'YYYY-mm-dd'
        """
        Fetch available heart rates data
        """
        getURL = self.url_heartrates + self.display_name + '?date=' + cdate
        try:
            response = self._session.get(getURL, headers=self.headers)
            response.raise_for_status()
        except requests.exceptions.HTTPError as e:
            self.logger.info(
                "Exception occured during heart rate retrieval - perhaps session expired - trying relogin: %s" % e)
            self._login(self._email, self._password)
            try:
                response = self._session.get(getURL, headers=self.headers)
                response.raise_for_status()
            except requests.exceptions.HTTPError as e:
                self.logger.error("Exception occured during stats retrieval, relogin without effect: %s" % e)
                return
        return response.json()
```

**Comment by cyberjunky** [comment]
Looks fine to me, updated my local code and testing, will let you know.
Did you manage to parse the heart-rates json output?

**Comment by psilo909** [comment]
what do you mean with "did you manage"?

i am getting a json array in the form: 'heartRateValues': [[1578438000000, 53], [1578438120000, 50], ...

currently trying to get this into a chart to visualize.. i still need to figure out how to transfer all these information into the item structure of our software.. i first thought about just pulling the data daily after 0:00, but if the watch is not synched, this wont help.

**Comment by psilo909** [comment]
concerning the parsin question:
![234](https://user-images.githubusercontent.com/15831643/72006550-2c495f80-3250-11ea-9e70-3cf8a7a11cb4.JPG)

**Comment by cyberjunky** [comment]
Yes that's what I mean, nice;-)
I have tested your fixes, and they worked repo is updated, thanks!
I left out the first request.get SIGNIN url, so only the post, and that worked too, did you try that as well?

**Comment by psilo909** [comment]
i see a post only in the login method, i did not touch the code there.

i think the relogin handling needs to be around the 2 gets wich retreive data?

**Comment by cyberjunky** [comment]
Yes the first get in login doesn't seem to be needed in the beginning.

**Comment by psilo909** [comment]
I did not check the login so far. Will have a look this weekend

**Comment by cyberjunky** [comment]
I have seen that during night hours 00-3hr the status is None for all returned items, status code is 200, and privacyProtected = False.  Will test some more.
![Capture](https://user-images.githubusercontent.com/5447161/72136772-d2e54b80-3389-11ea-8604-ba1a86a3be9e.GIF)

**Comment by cyberjunky** [comment]
Happened tonight again, I think the reason for the missing data (None values) is simply that on the new day without a sync you ask for data which isn't there yet.

**Comment by cyberjunky** [comment]
Will close this as issue seems solved by your code/latest library version.
