### ISSUE TITLE
basal_met = BMR = Caloric Intake ?

### ISSUE THREAD

**Issue by RobertWojtowicz** [cyberjunky/python-garminconnect#203]
Hi,

I use this great solution (I use them in my [miscale2garmin](https://github.com/RobertWojtowicz/miscale2garmin) project), I have a question if: basal_met = BMR = Caloric Intake?, if so this data does not appear in Garmin Connect, can you verify this?

![image](https://github.com/cyberjunky/python-garminconnect/assets/19271127/12ed165a-0eff-41c6-8670-eb7cb3e97ed5)

BR,
Robert

**Comment by psdupvi** [comment]
My suspicion is that `basal_met` is your [Basal Metabolic Rate](https://en.wikipedia.org/wiki/Basal_metabolic_rate), or BMR.  However, BMR is not the same as Caloric Intake.  It's the amount of calories you would burn any given day just by sitting there doing absolutely nothing

It does appear it's not displayed anywhere, it doesn't come back out in the endpoint `get_body_composition`, and it doesn't appear to update the Calories In/Out section in Garmin either.

So I don't think it does anything -- perhaps it used to but they changed it?

**Comment by RobertWojtowicz** [comment]
Thanks for the clarification,

I find it interesting that the Caloric Intake parameter that is in the weight section is not linked to calories from another section (there it is calculated somehow by Garmin + MyFitnessPal)

BR,
Robert
