### ISSUE TITLE
Set hydration data [Feature request]

### ISSUE THREAD

**Issue by svanhoutte** [cyberjunky/python-garminconnect#204]
Thanks for this great project !
@cyberjunky Would you be able to add a function to set the hydration data ? the same way you set the blood pressure data ? That would be really useful. 

thanks

**Comment by psdupvi** [comment]
It looks like the URL would be `usersummary-service/usersummary/hydration/log` or something similar, and the payload is 

```json
"calendarDate": "2024-05-15"
"timestampLocal": "2024-05-15T07:12:51.180"
"userProfileId": 71328280, 
"valueInML": 236.588
```

No matter which setting I use on GC (e.g., Ounces, Cups, or ml), the endpoint takes a "valueInML", never "valueInOz" or "valueInCups"

I can take a look at this after work today

**Comment by svanhoutte** [comment]
Thanks a lot @psdupvi

**Comment by psdupvi** [comment]
https://github.com/cyberjunky/python-garminconnect/pull/205

This will be available when merged, but if you want to start early, the code is visible there and can be copied (from `__init__.py`, you'll need the URL and the function definition)

Call looks like this:
`api.add_hydration_data(value_in_ml=240,cdate='2024-05-15',timestamp='2024-05-15T09:50:42.257671')`

cdate and timestamp are both optional and default to now

**Comment by svanhoutte** [comment]
@psdupvi Thanks a lot, gonna test this asap !  hopefully today

**Comment by cyberjunky** [comment]
Closing this, since implemented by @psdupvi and requested and tested by @svanhoutte, thanks both!
