### ISSUE TITLE
features requset: support garmin-China(garmin.cn) and download activities after a certain time.

### ISSUE THREAD

**Issue by yihong0618** [cyberjunky/python-garminconnect#21]
Hi, 
thank you for your great job for this repo.

1. Beacause I am working on [running_page](https://github.com/yihong0618/running_page) to support garminconnect
I run in China, and there's a different api for Chinese runners,  like https://connect.garmin.cn/modern/
except for the `cn` instead of `com`, others are the same.
like below
![image](https://user-images.githubusercontent.com/15976103/95717230-385ec380-0c9f-11eb-9c8e-f898d06dc68a.png)
can we offer a parameter like cn for Chinese runners?
something like this
```python
client = Garmin(YOUR_EMAIL, YOUR_PASSWORD, is_cn=True)
```
2. because I download every day gpx using [GitHub Actions](https://github.com/yihong0618/running_page/blob/master/.github/workflows/run_data_sync.yml) so if we can only download the activities after a certain time will be wonderful. like my [runtastic repo](https://github.com/yihong0618/Runtastic) do.

Can I take a pr for these features?

**Comment by cyberjunky** [comment]
@yihong0618 If you want to contribute with a PR, please do so! If not let me know, and I can implement it, when I find some time.

**Comment by yihong0618** [comment]
@cyberjunky 
Got it, will do this in this weekend thank you~

**Comment by yihong0618** [comment]
@cyberjunky 
This [PR](https://github.com/cyberjunky/python-garminconnect/pull/43) support connect.garmin.cn

**Comment by yihong0618** [comment]
I think there is no need to support after a certain
Because we hava `get_activities_by_date` now.

So this issue can be closed

**Comment by cyberjunky** [comment]
@yihong0618 I see you have used my code in your project and made it async, nice. Wanted to do that too.
