### ISSUE TITLE
Intensity minutes endpoint [I've this working but can't add the test]

### ISSUE THREAD

**Issue by shoaib42** [cyberjunky/python-garminconnect#220]
I've adding the following endpoint and method to get the intensity minutes, would like to contribute but I'm unable to make heads and tails out of the test setup. I can't share cred, so how do I go about this? Create a PR and take it from there?

```
    # in init
         self.garmin_connect_daily_intensity_minutes = (
            "/wellness-service/wellness/daily/im"
        )
    #

    def get_intensity_minutes_data(self, cdate: str) -> Dict[str, Any]:
        """Return available Intensity Minutes data 'cdate' format 'YYYY-MM-DD'."""

        url = f"{self.garmin_connect_daily_intensity_minutes}/{cdate}"
        logger.debug("Requesting Intensity Minutes data")
```

**Comment by psdupvi** [comment]
Yeah, go ahead and set up a PR! We can always add tests/changes if necessary. My first few commits here I didn't include any tests, and it was ok (the maintainer very nicely took care of that while I figured my stuff out)

**Comment by shoaib42** [comment]
@psdupvi Thanks! PR opened https://github.com/cyberjunky/python-garminconnect/pull/227

**Comment by cyberjunky** [comment]
@shoaib42 @psdupvi added to 0.2.20 version again thanks both!
