### ISSUE TITLE
Question: Can you pull heart-rate data for a full day?

### ISSUE THREAD

**Issue by OhioAdam** [cyberjunky/python-garminconnect#23]
So far from what I can tell you can only get heart-rate data for the intervals within an activity. Is there a way to pull all hear-rate data for a particular day?

**Comment by cyberjunky** [comment]
@OhioAdam I'm niot sure if this is possible, or better, if we know ow to get that data,

**Comment by cyberjunky** [comment]
@OhioAdam I'm not sure have to investigate, another users implemented the heart rate fetching code I think, will come back to you

**Comment by OhioAdam** [comment]
Okay thanks @cyberjunky . Every time I've tried I only get a small window of heart-rate data for the duration of a specific activity. I will stay tuned

**Comment by petz15** [comment]
Hey, I was able to get my heartrate from the entire day with "get_heart_rate". Maybe it's a device specific issue i.e. your device does not have that kind of data. You should see if the garmin connect dashboard has it in the first place.

**Comment by OhioAdam** [comment]
Thanks @petz15 . It's been a while since I looked at this. I'll give it a try and close this if that does the trick

**Comment by lokanx** [comment]
You could get heart rates for a day.
https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailyHeartRate/<your-username>?date=2021-06-08

**Comment by cyberjunky** [comment]
@OhioAdam Implemented as 'get_heart_rates' in 0.1.24 soon to be released
