### ISSUE TITLE
Assertion Error?

### ISSUE THREAD

**Issue by 3NJDGZ** [cyberjunky/python-garminconnect#238]
<img width="866" alt="image" src="https://github.com/user-attachments/assets/c8924bb1-881d-49a6-8b3f-1793fda23923">
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/5e89acd1-7ec8-46ac-853e-4fbd5c22f9da">

For some reason, I am getting an AssertionError both when I run my flask application, as well as from the example.py file provided by this repo? Has anyone else encountered this problem?

**Comment by 3NJDGZ** [comment]
It was working fine before with no assertion error (I have not changed any of the code).

**Comment by cyberjunky** [comment]
There is an issue with underlying lib because of API change by garmin https://github.com/cyberjunky/python-garminconnect/issues/235

**Comment by bobgott** [comment]
I'm seeing the exact same problem as @3NJDGZ .  I'll wait patiently for garth's fix to trickle into your next release (hopefully soon).

**Comment by eitanbehar** [comment]
same issue here, it worked fine until 25-Nov.
I was use an older library 0.2.8, upgraded to latest one 0.2.21, still same error 'AssertionError'

 ```
File "/src/Withings2Garmin/./sync.py", line 184, in <module>
    main()
  File "/src/Withings2Garmin/./sync.py", line 67, in main
    sync(**opts.__dict__)
  File "/src/Withings2Garmin/./sync.py", line 133, in sync
    garmin = init_garmin(garmin_username, garmin_password, verbose_print)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/Withings2Garmin/./sync.py", line 77, in init_garmin
    garmin.login(tokenstore)
  File "/usr/local/lib/python3.11/site-packages/garminconnect/__init__.py", line 230, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/garth/http.py", line 104, in profile
    assert isinstance(self._profile, dict)
AssertionError
```

**Comment by RobertWojtowicz** [comment]
> Temp fixed in version 0.2.22!

I confirm that it works :)

BR,
Robert

**Comment by eitanbehar** [comment]
> Temp fixed in version 0.2.22!

fix works for me also! thanks!!!!

**Comment by bobgott** [comment]
Works for me as well, Thank you for the quick action

**Comment by robquail** [comment]
I am suddenly seeing AssertionError with 0.2.23

```
garminconnect      0.2.23
garth              0.4.47
```

`garminconnect\__init__.py", line 208, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\robhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\garth\http.py", line 104, in profile
    assert isinstance(self._profile, dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError`

**Comment by robquail** [comment]
@cyberjunky is this still open?  See multiple success reports here and on above linked issue, but having no such luck with the above versions, is there something else I need to update?

`Traceback (most recent call last):
  File "d:\Rob\Documents\runs\app\garmin.py", line 65, in <module>
    update_db()
  File "d:\Rob\Documents\runs\app\garmin.py", line 24, in update_db
    garmin.login()
  File "C:\Users\robhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\garminconnect\__init__.py", line 208, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\robhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\garth\http.py", line 104, in profile
    assert isinstance(self._profile, dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError`

**Comment by robquail** [comment]
both garth and garminconnect updated but no luck still on this issue
`Successfully installed garminconnect-0.2.24 garth-0.4.47`

also, while upgrading...
ERROR: pip's depe```
ndency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
garminconnect 0.2.24 require
```s garth==0.4.47, but you have garth 0.5.2 which is incompatible.

**Comment by cyberjunky** [comment]
@robquail did you also try the example.py script? I cannot reproduce the error, with garth 0.4.47 nor with 0.5.2

**Comment by cyberjunky** [comment]
I will release new version in a few minutes which uses garth 0.5.2

**Comment by robquail** [comment]
The example works, looks like I have some changes to make on my side which has always used plain strings for username and password in the Garmin() initialization call

**Comment by cyberjunky** [comment]
@robquail that's partly great news, let me know if you stumble upon something that should work but isn't, i believe they call it a 'bug' ;-)

**Comment by cyberjunky** [comment]
Ah ok, so the bug left!
