### ISSUE TITLE
Question: Is it possible to pull Activity's Laps Data

### ISSUE THREAD

**Issue by bobgott** [cyberjunky/python-garminconnect#24]
I'm trying to get an activity's Laps data. I didn't see it in your 'get_activities' or any method that might grab it.

Any help would be appreciated.

**Comment by bobgott** [comment]
OK, I'll answer my own question (after doing some digging).  It appears the Lap data is stuck in the TCX file contents.  I'm going to assume this is out of scope here .. as I can read the TCX and grab what I need.

**Comment by bobgott** [comment]
I'll assume this should be closed per my previous comment

**Comment by BenShutt** [comment]
A little late to this, perhaps it was different when you wrote that message.

Looking at the `Garmin` class, I can see there is this function that might be helpful

```python
api.get_activity_splits(activityId)
```

**Comment by bobgott** [comment]
You are correct, I have been successfully using `api.get_activity_splits(activityId)`
