### ISSUE TITLE
Question: Request limit

### ISSUE THREAD

**Issue by scimone** [cyberjunky/python-garminconnect#26]
Hi,
thank you for this amazing API!
I have used it a bit too enthusiastically and now get this error: "Error occurred during Garmin Connect Client login: Too many requests".
Do you know what the request limit is so I know it for future requests?

**Comment by gplasky** [comment]
Their API is not publicly documented as far as I can tell so I don't know if we'll ever know the exact answer to this. FWIW over the course of ~90 minutes I hit their API for login / data pulls no more than a few dozen times, so the limits are definitely *very low*  but it's unclear if they're hourly/daily quotas or rate-based. I'll see what happens tomorrow after giving this a rest for ~12 hours.

**Comment by cyberjunky** [comment]
@gplasky my Home Assistant integration https://www.home-assistant.io/integrations/garmin_connect/ polls every 10 minutes 24/7 that didn't gave any issues, but I don't know what the limit is.

**Comment by cyberjunky** [comment]
Stale issue, closing for now
