### ISSUE TITLE
Request for adding hydration data

### ISSUE THREAD

**Issue by zenelba** [cyberjunky/python-garminconnect#27]
I can not find hydration intake data.

Is it available thru any of the functions or new function is needed?

**Comment by cyberjunky** [comment]
@zenelba I have added a call in version 0.1.18, can you try it, I only found an URL to fetch daily.
It returns below data (I don't use it, so don't know if your data contains the requested info)

```
{'userId': xxxx, 'calendarDate': '2021-01-20', 'valueInML': None, 'goalInML': 2800.0, 'dailyAverageinML': None, 'lastEntryTimestampLocal': None, 'sweatLossInML': None, 'activityIntakeInML': None}
````

**Comment by zenelba** [comment]
Hi! 
Checked. It works - at least "valueInML". 
Will check also the others during the weekend.

THNX!

z
