### ISSUE TITLE
Question: Multiple Body Composition per day

### ISSUE THREAD

**Issue by richardswgoh** [cyberjunky/python-garminconnect#34]
On the presumption that I may weigh myself multiple times in one day, is it possible to retrieve all weigh-ins (body composition records) for any single day?

Currently result set returns the most-recent or max record for the provided date. Attempting to change the URL to retrieve a range of dates still only returns one per day. (e.g. https://connect.garmin.com/modern/proxy/weight-service/weight/daterangesnapshot?startDate=2021-01-01&endDate=2021-01-04)

**Comment by lokanx** [comment]
Yes you could implement it yourself using fetch_data method. Don't remember the url but you could see it in the web browser when navigating to the weight  day view page.

**Comment by cyberjunky** [comment]
@richardswgoh This feature (from PR) didn't survive code updates, it's added back to 0.1.24 (soon to be released)
