### ISSUE TITLE
Force Logout Method

### ISSUE THREAD

**Issue by Webtron18** [cyberjunky/python-garminconnect#37]
I was just wondering if there was a method to force the session to log out. 
I am looking to pull two people data each morning back to back. I would login with one user, collect the necessary data, logout, login with the next user,collect, logout. 

I was trying to see if there was a simple way of doing this.

**Comment by cyberjunky** [comment]
@Webtron18 it seems calling /auth/logout/?url= does this, will try to implement it.

**Comment by cyberjunky** [comment]
@Webtron18 Added to 0.1.24 soon to be released
