### ISSUE TITLE
Recovery time

### ISSUE THREAD

**Issue by mconning** [cyberjunky/python-garminconnect#38]
Is it possible to get access to the recovery time metric that is made available after each training session? I have looked at all the stats available currently but can't find it.

**Comment by mconning** [comment]
Btw, this is a great repo to get access to Garmin data, thank you!

**Comment by cyberjunky** [comment]
Hi, thanks. Is it visible on the connect.garmin.com site somewhere? If so under which url? We have to reverse engineer it ;-)
What I found so far is that it's displayed together with vo2max on some watches...

**Comment by mconning** [comment]
I just did a search for it and can't find it there. A few forums also mention that it is not available, so I guess I'm out of luck. It shows only on the device, so if I want to get access to it, I probably have to get access to the device data. Thanks anyway, good to know that if I want to get access to anything it needs to be available on Garmin Connect specifically.

**Comment by cyberjunky** [comment]
Yes it's seems to be calculated locally and not synced, I will have a look at the java-script code on the site, maybe they have it, but not yet displaying it.

**Comment by mconning** [comment]
Awesome, thank you!

**Comment by cyberjunky** [comment]
@mconning Nothing found in any of the javascript or website code, I'm afraid this is not possible.

**Comment by mconning** [comment]
Ah, thank you so much for having a look at it. I'll look for another way.
