### ISSUE TITLE
url_activities

### ISSUE THREAD

**Issue by enydog** [cyberjunky/python-garminconnect#39]
May be url_activities = MODERN_URL + '/proxy/activitylist-service/activities/search/activities' 
was changed.

Garmin CLIENT ok
Garmin LOGIIN ok
Error occurred during Garmin Connect Client get activities: Error connecting

**Comment by JVPA** [comment]
I have the same problem garminconnect.GarminConnectConnectionError: Error connecting

**Comment by enydog** [comment]
BASE_URL = 'https://connect.garmin.com'
SSO_URL = 'https://sso.garmin.com/sso'
MODERN_URL = 'https://connect.garmin.com'
#MODERN_URL = 'https://connect.garmin.com/modern'
SIGNIN_URL = 'https://sso.garmin.com/sso/signin'

**Comment by cyberjunky** [comment]
@enydog thanks!
Please try version 0.1.19

**Comment by JVPA** [comment]
I have tried the last version and the problem is solved

> @enydog thanks!
> Please try version 0.1.19

I have tried the last version and the problem is solved

**Comment by cyberjunky** [comment]
I will close this ticket, users of Home Assistant can run a beta version, or wait until Wednesday for the fix to be included in the new release.
