### ISSUE TITLE
Latest pip release doesn't match github master

### ISSUE THREAD

**Issue by Etragas** [cyberjunky/python-garminconnect#4]
Hey there!
The most recent version of this repo on pip is 0.1.8 but when I download the files they don't align with master. But 0.1.7 (released on Jan 19) seems to align.

Is it possible 0.1.8 was an accidental release?

**Comment by cyberjunky** [comment]
Thanks for noticing..0.1.8 had some minor changes, and I simply forgot to push the lastest code to github.
I have fixed this, and also released 0.1.9.
