### ISSUE TITLE
402 Errors

### ISSUE THREAD

**Issue by burnsge** [cyberjunky/python-garminconnect#40]
Thanks for a very useful tool - unfortunately, this afternoon (02/23/2021) I have started getting 402 - Payment Required errors on most of the data request functions in this software (device last used, stats, steps, devices, hydration, statistics, etc.). I appear to have a viable connection through the initial stages of logging in, as functions like client.get_full_name() seem to return the expected values without any trouble. Any insights would be much appreciated.

**Comment by lokanx** [comment]
I have the same problem, seems they changed something on their side.

**Comment by cyberjunky** [comment]
It's clear they have changes thinks, maybe check for validity of the requests, I will have a look.

**Comment by sjeri** [comment]
> It's clear they have changes thinks, maybe check for validity of the requests, I will have a look.

There is this 'NK': 'NT' header which seem to be checked now. Was only the case for post requests so far.

**Comment by Johne3112** [comment]
I changed MODERN_URL to 'https://connect.garmin.com' (removed /modern) and that seems to work

**Comment by enydog** [comment]
yes https://connect.garmin.com 
but some url fails.

https://connect.garmin.com/proxy/usersummary-service/usersummary/daily/

**Comment by cyberjunky** [comment]
Please try version 0.1.19

**Comment by lokanx** [comment]
The fix works perfect, thanks for the fast fix 👍  🥇

**Comment by cyberjunky** [comment]
I will close this ticket, users of Home Assistant can run a beta version, or wait until Wednesday for the fix to be included in the new release.
