### ISSUE TITLE
client.get_stats(today.isoformat()) fails as of today (Feb 23 2021)

### ISSUE THREAD

**Issue by RobertHenschel** [cyberjunky/python-garminconnect#41]
I assume this is related #39 and #40. As of today, client.get_stats(today.isoformat()) fails with a JSONDecodeError exception.

**Comment by cyberjunky** [comment]
Please try version 0.1.19

**Comment by jhurl3y** [comment]
0.1.19 doesn't work for me, get a `GarminConnect error: Error connecting`

**Comment by jhurl3y** [comment]
```
DEBUG:urllib3.connectionpool:https://connect.garmin.com:443 "GET /modern/proxy/wellness-service/wellness/dailySummaryChart/056406fd-2fa5-4ff3-8a42-a4d2ea904e67?date=2021-02-23 HTTP/1.1" 402 0
DEBUG:garminconnect:Fetch response code 402
DEBUG:garminconnect:Exception occurred during data retrieval, relogin without effect: 402 Client Error: Payment Required for url: https://connect.garmin.com/modern/proxy/wellness-service/wellness/dailySummaryChart/056406fd-2fa5-4ff3-8a42-a4d2ea904e67?date=2021-02-23
```

**Comment by cyberjunky** [comment]
@jhurl3y I think you are still using the old version since the log contains 'modern' in urls. Can you try 0.1.19?

**Comment by adelehirst** [comment]
Hi, where can i find the dl for  0.1.19 ?  many thanks, Adele.

**Comment by RobertHenschel** [comment]
Thanks @cyberjunky. I can confirm that version 1.19 works! Thanks so much for the quick fix!

@adelehirst, you can try upgrade your package with:
`pip install garminconnect --upgrade`

**Comment by adelehirst** [comment]
@cyberjunky   many thanks.....   yes it worked treat....  can see im out of practice/total newbie hahah

**Comment by jhurl3y** [comment]
I'm on the correct version I think:
```
(base) ➜  garmin-api git:(master) ✗ pip freeze | grep garminconnect
garminconnect==0.1.19
```

Did we update all the urls?

**Comment by cyberjunky** [comment]
The word 'modern' cannot be found in the source code anymore, so yes we changed them all, it looks like some old module is hanging around on your system?
https://github.com/cyberjunky/python-garminconnect/blob/master/garminconnect/__init__.py

You searched in the repo directory on your system I see, was it installed as well? Otherwise it will only use that version when run from that directory.

**Comment by adelehirst** [comment]
any ideas where running power would be found ?

**Comment by jhurl3y** [comment]
ok perfect. I'll dig into this properly and update here. Thanks very much!

**Comment by cyberjunky** [comment]
I will close this ticket, users of Home Assistant can run a beta version, or wait until Wednesday for the fix to be included in the new release.
