### ISSUE TITLE
Power Data

### ISSUE THREAD

**Issue by adelehirst** [cyberjunky/python-garminconnect#42]
Not an issue as such, but does this api wrapper provide access to the running power data field within garmin ?  i have had a look at get_activity_details and download_activity, but can't see any obvious field.... 

Many thanks for any pointers.

Adele.

**Comment by cyberjunky** [comment]
@adelehirst I can have a look, is it visible on the connect.garmin.com website, if so, under which menu/url?

**Comment by adelehirst** [comment]
hmmm i'm not sure whether it is......  basically my background, husband is the runner and i work in data science/BI  .... realised how much data he's spooling on his garmin so thought ace opportunity to use to learn python more....    

he's measuring his power via a Styrd footpod he says feeds into his garmin watch... however after poking around garmin connect web version i can't see where power is recorded (apart from one field relating to cycling power i believe)...  i have since investigated his phone garmin app and found there is a Connect IQ widget called 'Styde Zones Data Field' that links to styde i think for power values ....  where would the data in these be found?  what is confusing me is i can't find 'Styde Zones Data Field' on the garmin connect web version?   anyone any ideas?

Also i see garmin have https://developer.garmin.com/connect-iq/api-docs/  how does this relate to the python libriaries here?   sorry my background is really sql programming....  although i have studied java during my degree many yrs ago i'm so rusty with more object orientated approach

many thanks again!

**Comment by cyberjunky** [comment]
Some data only seems available on the watch devices, and doesn't seem to be available in Garmin connect side, at least not found yet. This library is for Garmin connect, and the one you found is for ConnectIQ, that's more related to the Garmin device Firmware and Apps, not sure if you can get same data out of it than mine does, looks interesting though.
