### ISSUE TITLE
"Payment Required" to access garmin connect activities api?

### ISSUE THREAD

**Issue by fvanoostrom** [cyberjunky/python-garminconnect#44]
I get this error when trying to fetch new activities:

> 402 Client Error: Payment Required for url: https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?startDate=2021-02-19&endDate=2021-03-08&start=0&limit=20

A few weeks ago I got messages about reaching the api limit although I hadn't used it for days. But this message seems to indicate that garmin made changes to the api which the garmin connect library uses? I can't find the documentation of garmin about the API. 

Has garmin indeed made changes and do we need to pay?

**Comment by fvanoostrom** [comment]
An update to the library seems to have resolved it. I'm curious to what has changed to fix this issue since it looks like a very basic operation (the URL seemed correct, login was succesfull)

**Comment by cyberjunky** [comment]
@fvanoostrom the fix was simply a change of the base url, see here:

https://github.com/cyberjunky/python-garminconnect/commit/daba147c94b1d733151848603e9f1b4c38c0b031

**Comment by gplasky** [comment]
@cyberjunky Pardon the bump of a closed issue -- I've been unable to find any public documentation about the Garmin Connect API -- how are you figuring these things out? :) I assume you have a business developer account from https://developer.garmin.com/gc-developer-program/activity-api/ or are you doing some serious reverse-engineering?

**Comment by cyberjunky** [comment]
I believe the developer program costs 5K EUR to join and only 'skilled developers' with track records may join, so i'm open for donations ;-) The code has parts of other open-source projects and other links were reverged enginered from the website javascript source code.
