### ISSUE TITLE
garminconnect module not installed error when try to use in SQL server

### ISSUE THREAD

**Issue by adelehirst** [cyberjunky/python-garminconnect#45]
hi,

i have been playing about with this garminconnect module from within cmd line, however, i'm looking at running a python script within my local sql server to extract garmin data straight into a db table.... however, when trying to exec a script within sql server i get an error of : 

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:\ProgramData\MSSQLSERVER\Temp-PY\Appcontainer1\5900CC12-8793-4B57-9E70-CAC90E5779DE\sqlindb_0.py", line 33, in transform
    import garminconnect as gd
ModuleNotFoundError: No module named 'garminconnect'

SqlSatelliteCall error: Error in execution.  Check the output for more information.

ANyone any experience of using this from within a script in sql?  

thanks,

Adele.

**Comment by cyberjunky** [comment]
Not supporting MSSQL and stale ticket so closing.
