### ISSUE TITLE
Error https://sso.garmin.com/sso/signin

### ISSUE THREAD

**Issue by enydog** [cyberjunky/python-garminconnect#46]
Login to Garmin Connect using POST url %s https://sso.garmin.com/sso/signin
Error occurred during Garmin Connect Client login: Error connecting

**Comment by Jetsukda** [comment]
I had this problem too.

**Comment by alan-couzens** [comment]
Ditto. It looks like a new csrf token has now been added to the Garmin Connect sign-in that needs to be pulled from the header or the text of the sign-in page & passed with the other sign-in parameters.

**Comment by cyberjunky** [comment]
A running session with current tokens worked, but started new session and have same issue indeed, needs investigation, any help is welcome

**Comment by enydog** [comment]
https://sso.garmin.com/sso/login?service=https://connect.garmin.com/modern/&webhost=https://connect.garmin.com&gateway=true&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=true

**Comment by yihong0618** [comment]
@cyberjunky 
I worked on it for a few hours. No luck, the security is based on the Cloudflare
not only added a `csrf token` but also when we post login casued a Cloudflare security issue.
![Uploading image.png…]()

**Comment by enydog** [comment]
yes.
Cache-Control=no-cache
Connection=keep-alive
Date=Tue, 18 May 2021 10:54:20 GMT
Transfer-Encoding=chunked
Content-Type=text/html; charset=UTF-8
Last-Modified=Tue, 27 Apr 2021 15:11:58 GMT
Accept-Ranges=bytes
Server=cloudflare
x-frame-options=deny
CF-Cache-Status=DYNAMIC
cf-request-id=0a20b5d687000074ef948d3000000001
Expect-CT=max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
CF-RAY=65148c040efd74ef-EZE

**Comment by Jetsukda** [comment]
> yes.
> Cache-Control=no-cache
> Connection=keep-alive
> Date=Tue, 18 May 2021 10:54:20 GMT
> Transfer-Encoding=chunked
> Content-Type=text/html; charset=UTF-8
> Last-Modified=Tue, 27 Apr 2021 15:11:58 GMT
> Accept-Ranges=bytes
> Server=cloudflare
> x-frame-options=deny
> CF-Cache-Status=DYNAMIC
> cf-request-id=0a20b5d687000074ef948d3000000001
> Expect-CT=max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> CF-RAY=65148c040efd74ef-EZE

@enydog can  you show how to fix this bug in code ?

**Comment by enydog** [comment]
> > yes.
> > Cache-Control=no-cache
> > Connection=keep-alive
> > Date=Tue, 18 May 2021 10:54:20 GMT
> > Transfer-Encoding=chunked
> > Content-Type=text/html; charset=UTF-8
> > Last-Modified=Tue, 27 Apr 2021 15:11:58 GMT
> > Accept-Ranges=bytes
> > Server=cloudflare
> > x-frame-options=deny
> > CF-Cache-Status=DYNAMIC
> > cf-request-id=0a20b5d687000074ef948d3000000001
> > Expect-CT=max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
> > CF-RAY=65148c040efd74ef-EZE
> 
> @enydog can you show how to fix this bug in code ?
Cloudflare.....
We have built security into every component of the network. Cloudflare’s 67 Tbps network blocks an average of 70 billion threats per day, including some of the largest DDoS attacks ever recorded. Each and every login, request, and response that goes through our network strengthens the machine learning that we apply to detect and block threats at the edge, before they ever reach your organization.

**Comment by Anrijs** [comment]
Using `cloudscraper` instead of `requests` worked for me: https://github.com/Anrijs/python-garminconnect/commit/4a4b33abf977499df4f08fa9fa028fbd5710ec33

**Comment by enydog** [comment]
> Using `cloudscraper` instead of `requests` worked for me: [Anrijs@4a4b33a](https://github.com/Anrijs/python-garminconnect/commit/4a4b33abf977499df4f08fa9fa028fbd5710ec33)

example please

**Comment by Jetsukda** [comment]
> > Using `cloudscraper` instead of `requests` worked for me: [Anrijs@4a4b33a](https://github.com/Anrijs/python-garminconnect/commit/4a4b33abf977499df4f08fa9fa028fbd5710ec33)
> 
> example please

chang requests to cloudscraper. it work!

**Comment by cyberjunky** [comment]
I have just created release 0.1.20 with cloudscraper tweak by enydog, thanks!
Can someone try it?

**Comment by Jetsukda** [comment]
> I have just created release 0.1.20 with cloudscraper tweak by enydog, thanks!
> Can someone try it?

I'm stuck with some BUG. but i try to debug it.

**Comment by cyberjunky** [comment]
I mean thanks @Anrijs and others!

**Comment by cyberjunky** [comment]
You need to run " python ./setup.py install " once.

**Comment by Anrijs** [comment]
> I mean thanks @Anrijs and others!
I think GET must be also called before login POST to get cookies and stuff. Otherwise it won't work (Lines 111-113 in my example).

**Comment by cyberjunky** [comment]
If run from source, I have not put it on PyPi yet

**Comment by cyberjunky** [comment]
> > I mean thanks @Anrijs and others!
> 
> I think GET must be also called before login POST to get cookies and stuff. Otherwise it won't work (Lines 111-113 in my example).

Ah I overlooked those, strangly enough the exmple code still worked, maybe cloudflare is not the same worldwide (new version rollout or something) 
Will create 0.1.21 in a sec

**Comment by yihong0618** [comment]
@Anrijs Cool. Thanks，and we do not need csrf token，a little strange

**Comment by Jetsukda** [comment]
Thanks  @Anrijs

**Comment by cyberjunky** [comment]
I have put out release 0.1.21, if it works for people (if possible to test) I will upload to PyPi so pip install works.
Thanks!

**Comment by cyberjunky** [comment]
Wrong button ;-)

**Comment by cyberjunky** [comment]
pip3 install garminconnect
or
pip3 install --upgrade garminconnect

Should work as well now to upgrade

**Comment by BebeMischa** [comment]
tell me, where and how i have to upgrade step by step on HA supervised, please, i will test... ;-) I'm not a coder, but can follow instructions very well :-)

**Comment by cyberjunky** [comment]
Hmm, I tried to create a guide for you, but garmin_connect doesn't appear to work when placed under "custom_components/garmin_connect"

I get the error "Unable to prepare setup for platform garmin_connect.sensor: Platform not found (cannot import name 'DeviceInfo' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py))"

Any of the devs knows why?

BTW: This is independent from the issue itself.

**Comment by cyberjunky** [comment]
Above is for Home Assistant btw.

**Comment by enydog** [comment]
Thanks @Anrijs and cyberjunky

**Comment by cyberjunky** [comment]
I can run the example script with all the queries over and over again (20 times or more) without getting a requesttomany response.
Perhaps this is fixed to by the changes, or by using the Cloudscraper module?

Can anyone confirm?

**Comment by enydog** [comment]
They also changed this endpoint.

    def get_excercise_sets(self, activity_id):
        activity_id = str(activity_id)
        exercisesetsurl = f"{self.url_activity}{activity_id}/exerciseSets"

result
{"activityId": 6799891126, "exerciseSets": null}

**Comment by enydog** [comment]
for this 

def get_excercise_sets(self, activity_id):
    activity_id = str(activity_id)
    exercisesetsurl = f"{self.url_activity}{activity_id}"

**Comment by cyberjunky** [comment]
@enydog, thanks, changed is in local code, for version 0.1.22

**Comment by Denis-81** [comment]
You guys are fantastic - thank you so much for your committment and creativity to get these things fixed in no time!!

**Comment by cyberjunky** [comment]
Fixed in latest version
