### ISSUE TITLE
Unknown error occurred during Garmin Connect Client get body composition

### ISSUE THREAD

**Issue by abdullah249** [cyberjunky/python-garminconnect#47]
hi,Can anyone help me with this issue? 

DEBUG:garminconnect:Fetching body composition with url https://connect.garmin.com/modern/proxy/weight-service/weight/daterangesnapshot?startDate=2021-05-19&endDate=2021-05-19
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): connect.garmin.com:443
DEBUG:urllib3.connectionpool:https://connect.garmin.com:443 "GET /modern/proxy/weight-service/weight/daterangesnapshot?startDate=2021-05-19&endDate=2021-05-19 HTTP/1.1" 402 0
Unknown error occurred during Garmin Connect Client get body composition

**Comment by cyberjunky** [comment]
Do you use the latest version 0.1.21?
