### ISSUE TITLE
name 'requests' is not defined

### ISSUE THREAD

**Issue by lokanx** [cyberjunky/python-garminconnect#48]
Hi!
After I have login I poll for new data every 10th min and it's working fine for a day. But suddenly I get errors: name 'requests' is not defined.

I suspect it comes from the error handling where you refer to requests.execeptions Like this:

`except requests.exceptions.HTTPError as err:            raise GarminConnectConnectionError("Error connecting") from err`

But requests are never imported so I suspect I breaks due to that, and the real error is lost (probably session timeout). Or have i missed something how it works?

Thanks for a great library.

Cheers Björn

**Comment by yihong0618** [comment]
```
import requests
```
In the front.
