### ISSUE TITLE
get_stats_and_body throws TypeError

### ISSUE THREAD

**Issue by jlapenna** [cyberjunky/python-garminconnect#5]
```
Traceback (most recent call last):
  File "/home/jlapenna/code/bikebuds/gae/backend/main.py", line 199, in _do
    getattr(worker, method)()  # Dynamically run the provided method.
  File "/home/jlapenna/code/bikebuds/gae/backend/services/garmin/garmin.py", line 34, in sync
    self.sync_measures()
  File "/home/jlapenna/code/bikebuds/gae/backend/services/garmin/garmin.py", line 41, in sync_measures
    logging.debug('XXX: %s', self.client.get_stats_and_body(now.isoformat()))
  File "/tmp/tmpnngZlI/lib/python3.7/site-packages/garminconnect/__init__.py", line 146, in get_stats_and_body
    return self.get_stats(cdate) + self.get_body_composition(cdate)
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
```

**Comment by cyberjunky** [comment]
Hi I haven't seen this yet.
Which kind of Scale or Weight measuring App do you use with your Garmin account?
Are you able to supply debug log info regarding the 2 returned json strings?
Make sure your display-name is hidden/anonymized.

**Comment by jlapenna** [comment]
response.json() returns a dict; and you return that in both of your
getters; your helper method adds them together, however, python doesn't
support adding two dicts:

In [1]: {} + {}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-03eea6c7a00d> in <module>()
----> 1 {} + {}

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

**Comment by cyberjunky** [comment]
Ah you are right, in my own code I call the routines get_stats() and  get_body_composition()
myself and add results together like so:

```python
self._data = {
            **activity_data,
            **body_composition_data,
        }
```

will have a look.

**Comment by cyberjunky** [comment]
I have created 0.1.10 can you give it a go?

**Comment by cyberjunky** [comment]
I close it, if you run into something please open again
