### ISSUE TITLE
Fetching recovery time

### ISSUE THREAD

**Issue by j4nSolo** [cyberjunky/python-garminconnect#51]
I was wondering if there's any API call that would return the "recovery time" as measured by some of the watches (for instance on my FR945). 

Since neither Connect (Android app) nor connect.garming.com are providing that information, I'm assuming it isn't gonna be on their API. If that's the case, I'd be ok with just cancelling this issue.

Thanks in advance!

![20210608_174843_HDR](https://user-images.githubusercontent.com/14826527/121217289-fe6fac80-c881-11eb-8bda-ea9acecc3601.jpg)

**Comment by enydog** [comment]
Recovery time copyright of firstbeatanalytics 
https://www.firstbeatanalytics.com/en/features/recovery-time/

live function of  (Stress levels, New sleep rate, Additional training Intensity ,Daily activity levels)

**Comment by WRPSoft** [comment]
As far as I know the recovery time is embedded in the activity's fit file. You can extract this value, if you're able to parse the belonging fit file. But recovery time is not declared in the FIT SDK, it's present in the EventMesg and can be extracted by GetData method from fit_mesg_with_event.hpp (Fit SDK) for example.

**Comment by cyberjunky** [comment]
@j4nSolo Did some research again, but it only seems available on watch itself so closing for now until new information comes up.
