### ISSUE TITLE
download ground contact time and vertical oscillation data from my stryd

### ISSUE THREAD

**Issue by peewel** [cyberjunky/python-garminconnect#56]
I am using the API for downloading all my split data from Garmin Connect. It works very well, thanks a lot for that!

I use a Stryd and in the current API, I can only download the power readings, as 'connectIQMeasurement' via client.get_activity_splits. But there is more data in garmin Connect: Ground (Contact) Time, Vertical Oscillation, Form Power, Leg Spring Stiffness, ....

I there a way to download that as well? Or does it need a change of the API. In that case, can that be arranged?

**Comment by dpupkov** [comment]
@peewel  You can use "client.get_activity_details". Frome there you would need to look into connectIQDeveloperField.

**Comment by peewel** [comment]
Hi Dmitry, many thanks! 
I tried that before but it seemed to be empty. But apparently, Eclipse just does not show it because it is too large.
When looking into it, I can indeed identify some of the connectIQMeasurement parameters. This is what I think is shown:


metricsIndex': 15 | 'key': 'connectIQDeveloperField00' | 'developerFieldNumber': 0 | Power (W)
metricsIndex': 16 | 'key': 'connectIQDeveloperField02' | 'developerFieldNumber': 3 | Ground Contact Time (ms)
metricsIndex': 17 | 'key': 'connectIQDeveloperField04' | 'developerFieldNumber': 8 | Form Power (W)
metricsIndex': 18 | 'key': 'connectIQDeveloperField06' | 'developerFieldNumber': 7 | ?
metricsIndex': 19 | 'key': 'connectIQDeveloperField08' | 'developerFieldNumber': 5 | ? Speed (m/s)
metricsIndex': 21 | 'key': 'connectIQDeveloperField10' | 'developerFieldNumber': 15 | ?
metricsIndex': 22 | 'key': 'connectIQDeveloperField01' | 'developerFieldNumber': 2 | ?
metricsIndex': 23 | 'key': 'connectIQDeveloperField03' | 'developerFieldNumber': 4 | Vertical Oscillation (cm)
metricsIndex': 24 | 'key': 'connectIQDeveloperField05' | 'developerFieldNumber': 9 | LSS (kN/m)
metricsIndex': 25 | 'key': 'connectIQDeveloperField07' | 'developerFieldNumber': 11 | ?
metricsIndex': 26 | 'key': 'connectIQDeveloperField09' | 'developerFieldNumber': 6 | ?
metricsIndex': 27 | 'key': 'connectIQDeveloperField11' | 'developerFieldNumber': 16 | ?

Is there any overview which can help me to complete this table?

**Comment by cyberjunky** [comment]
@peewel closing for now as it doesn't seem python-garminconnect related, please (re)open if needed.
