### ISSUE TITLE
how to get the gear for an activity (if needed)

### ISSUE THREAD

**Issue by proto-paul** [cyberjunky/python-garminconnect#57]
Not sure how interested you are but I worked out how to get the gear for an activity idea along the lines of
```
    BASE_URL = 'https://connect.garmin.com'
    url_gear = BASE_URL+'/proxy/gear-service/gear/filterGear?activityId='
    def get_gear(self, activity_id):
        activity_id = str(activity_id)
        gearurl = f"{self.url_gear}{activity_id}"
        self.logger.debug(f"Fetching gear for activity_id {activity_id}")
        return self.fetch_data(gearurl)
 ```
 I would be very interested in getting the training status/load/predicted times etc.. as related https://github.com/cyberjunky/python-garminconnect/issues/55
 I think they are related to the same url query but I was unable to work out how to get the info back.

**Comment by cyberjunky** [comment]
@proto-paul Thanks, will add it to version 0.1.24 as 'get_activity_gear'
