### ISSUE TITLE
New mod -> VIEWER_SOCIAL_PROFILE is not part of the response string.

### ISSUE THREAD

**Issue by enydog** [cyberjunky/python-garminconnect#58]
self.social_profile = self.parse_json(response.text, 'VIEWER_SOCIAL_PROFILE')
self.display_name = self.social_profile['displayName']
elf.full_name =self.social_profile['fullName']

**Comment by enydog** [comment]
**quick fix**  in garminClass.py

       #self.user_prefs = self.parse_json(
       #    response.text, 'VIEWER_USERPREFERENCES')
       #self.unit_system = self.user_prefs['measurementSystem']
      #self.logger.debug("Unit system is %s", self.unit_system)
       #self.social_profile = self.parse_json(
       #    response.text, 'VIEWER_SOCIAL_PROFILE')
       #elf.display_name = self.social_profile['displayName']
       #self.full_name = self.social_profile['fullName']
       #self.logger.debug("Display name is %s", self.display_name)
       #self.logger.debug("Fullname is %s", self.full_name)

        resp =self.fetch_data(self.url_activities)
        self.display_name = resp[0]['ownerDisplayName']
        self.full_name    =resp[0]['ownerFullName']
    
        print(self.full_name)
        self.logger.debug("Display name is %s", self.display_name)
        self.logger.debug("Fullname is %s", self.full_name)

**Comment by cyberjunky** [comment]
Already fixed days ago
