### ISSUE TITLE
Error connecting after 2021.12.21

### ISSUE THREAD

**Issue by nezinomas** [cyberjunky/python-garminconnect#60]
Latest version no longer connects to Garmin after 2012.12.21

----------------------------------------------------------------------------------------
client.login()
----------------------------------------------------------------------------------------
DEBUG:garminconnect:Login to Garmin Connect using POST url https://sso.garmin.com/sso/signin

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): sso.garmin.com:443

DEBUG:urllib3.connectionpool:https://sso.garmin.com:443 "GET /sso/signin?webhost=https%3A%2F%2Fconnect.garmin.com&service=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&usernameShown=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=false HTTP/1.1" 200 None

DEBUG:urllib3.connectionpool:https://sso.garmin.com:443 "POST /sso/signin?webhost=https%3A%2F%2Fconnect.garmin.com&service=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fsso.garmin.com%2Fsso%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&usernameShown=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=false HTTP/1.1" 403 None

Error occurred during Garmin Connect Client login: Error connecting

**Comment by RobertHenschel** [comment]
I am experiencing the same issue, and have not had time to look further into this.

**Comment by cyberjunky** [comment]
Found a solution, working on it..

**Comment by enydog** [comment]
https://github.com/cyberjunky/python-garminconnect/issues/58

**Comment by cyberjunky** [comment]
I was already fixed days ago.

**Comment by dpupkov** [comment]
@cyberjunky  Can you please update the package as well?
