### ISSUE TITLE
Forbidden URL during login since 2nd of January

### ISSUE THREAD

**Issue by terterwat** [cyberjunky/python-garminconnect#62]
ERROR:__main__:Error occurred during Garmin Connect communication: Forbidden url

Has there anything changed in 2022?

**Comment by cyberjunky** [comment]
Ignore it for now, it will retry and connect

**Comment by terterwat** [comment]
Thank you. 
It reconnects and works again

**Comment by psilo909** [comment]
I need to hook into this: I am using your PyPi package (0.1.28) as a plugin of our software "SmartHomeNG". The plugin only runs the "login" method once and then throws the "Forbidden" error.

When I run your example code via CLI, also the first call produces the error. The 2nd time it then works. Is there any way to do the same from my plugin? E.g. running the login method twice? Not sure what the reason behind is?

**Comment by psilo909** [comment]
I now did something like this, which seems to avoid the exception:
```
        try:
            self._api = Garmin(self._username, self._password, is_cn=self._is_cn)

            ## Login to Garmin Connect portal
            self._api.login()
            # USER INFO

            # Get full name from profile
            self.logger.info(self._api.get_full_name())

            ## Get unit system from profile
            self.logger.info(self._api.get_unit_system())
        except (
                GarminConnectConnectionError,
                GarminConnectAuthenticationError,
                GarminConnectTooManyRequestsError,
        ) as err:
            self._api = Garmin(self._username, self._password, is_cn=self._is_cn)
            self._api.login()
            self.logger.error("Error occurred during Garmin Connect communication: %s", err)
```

**Comment by cyberjunky** [comment]
@psilo909 I was wading through the debug information as well, but didn't have enough time, I will try your fix too, and let you know!

**Comment by cyberjunky** [comment]
@psilo909 Strange thing is when I try from CLI it works every time, just not always from home assistant, I suspect the User-Agent or a data fetch call too soon is the problem, but need to look into it some more

**Comment by psilo909** [comment]
yes it could also be a timing issue here.

**Comment by cyberjunky** [comment]
Didn't know SmartHomeNG's Garmin data looked so nice!

**Comment by psilo909** [comment]
I also just realized the session/login times out after a time.. I now added a sep. login method which is being run before each data retreival:
```
    def login(self):
        try:
            self._api = Garmin(self._username, self._password, is_cn=self._is_cn)
            self._api.login()
            self.logger.info(self._api.get_full_name())
            self.logger.info(self._api.get_unit_system())
        except (
                GarminConnectConnectionError,
                GarminConnectAuthenticationError,
                GarminConnectTooManyRequestsError,
        ) as err:
            self._api = Garmin(self._username, self._password, is_cn=self._is_cn)
            self._api.login()
            self.logger.error("Error occurred during Garmin Connect communication: %s", err)
```

also with restarts, the calls in the exception block seem to fix the issue. (still dont understand why, and even why the ERROR log is then not being printed)

**Comment by psilo909** [comment]
for the data: its a just a proprietary implementation of the web interface. still need to add "real" functionality to my plugin.

**Comment by psilo909** [comment]
the logout also just caused an exception (suppose empty json):
```
> Traceback (most recent call last):
>   File "/python/smarthome/lib/plugin.py", line 684, in stop
>     self.plugin.stop()
>   File "/python/smarthome/plugins/garminconnect/__init__.py", line 66, in stop
>     self._api.logout()
>   File "/usr/local/lib/python3.7/dist-packages/garminconnect/__init__.py", line 553, in logout
>     self.modern_rest_client.get(self.garmin_connect_logout).json()
>   File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 910, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cyberjunky** [comment]
Got logout fixed locally, thanks, was calling  `self.modern_rest_client.get(self.garmin_connect_logout).json()` , removed last part, will create new version soon.

**Comment by psilo909** [comment]
hmm running login for each data retreival now results in HTTPError:  429  Client  Error:  Too  Many  Requests  for  url:  https://sso.garmin.com/sso/signin

**Comment by cyberjunky** [comment]
There was something like that in the old code, where it would retry under certain circumstances... have to look it up

**Comment by cyberjunky** [comment]
While testing I got this response... seems things changed again... Payment required??
```
equests.exceptions.HTTPError: 402 Client Error: Payment Required for url: https://connect.garmin.com/modern/proxy/usersummary-service/usersummary/daily/5da0f071-075e-438c-ae63-xxxxxxxxxxxx?calendarDate=2022-01-06
```

Maybe need to look out for a Google Watch soon... :sob:

**Comment by cyberjunky** [comment]
The headers can trigger this.. LOL

**Comment by psilo909** [comment]
Please dont get a google watch ;-) my fenix 6 pro rocks pretty much - at least as a watch ;-) the api of garmin never was good though...

**Comment by cyberjunky** [comment]
I contacted Garmin a while ago to get official API doucmentation/access for Home Assistant integration, but they don't support open-source projects due to the fact that you get a key to use. I'm happy with my Garmin too, (vivoactive 4) but this hassling with errors/code is annoying.

**Comment by bidspells** [comment]
I experienced the same problems as described above with the current version 0.1.40. Then I sign into Garmin Connect manually using their web interface. Garmin is asking to agree to a new consent. After I agreed, the garminconnect wrapper works like a charm!

**Comment by cyberjunky** [comment]
Strange thing is that if you retry the request it usually works as well. But will have another look.

**Comment by psilo909** [comment]
tried the newest pypi package and am still getting the Error occurred during Garmin Connect communication: Forbidden url: https://sso.garmin.com/sso/signin

i dont see any consent thing on https://connect.garmin.com/modern/

@bidspells where did you log in?

**Comment by cyberjunky** [comment]
The research I did showed that the problem is with the post call.
It gives a different response sometime, a retry usually fixes it.
https://github.com/cyberjunky/python-garminconnect/blob/bc0a3a37f4ee82492e45abbdde333d3aa488e9ae/garminconnect/__init__.py#L278

Could be a cloudflare/garminconnect captcha or something, have to look at the source code returned..
I looked for another python package to go around cloudflare's AIM page, but only found very old ones.

**Comment by jasonmarkperez** [comment]
I'm also getting this, even when attempting to a login via CLI.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 86, in post
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sso.garmin.com/sso/signin?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&webhost=https%3A%2F%2Fconnect.garmin.com&source=https%3A%2F%2Fconnect.garmin.com%2Fen-US%2Fsignin&redirectAfterAccountLoginUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&redirectAfterAccountCreationUrl=https%3A%2F%2Fconnect.garmin.com%2Fmodern&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&locale=en_US&id=gauth-widget&cssUrl=https%3A%2F%2Fstatic.garmincdn.com%2Fcom.garmin.connect%2Fui%2Fcss%2Fgauth-custom-v1.2-min.css&privacyStatementUrl=%2F%2Fconnect.garmin.com%2Fen-US%2Fprivacy%2F&clientId=GarminConnect&rememberMeShown=true&rememberMeChecked=false&createAccountShown=true&openCreateAccount=false&displayNameShown=false&consumeServiceTicket=false&initialFocus=true&embedWidget=false&generateExtraServiceTicket=true&generateTwoExtraServiceTickets=false&generateNoServiceTicket=false&globalOptInShown=true&globalOptInChecked=false&mobile=false&connectLegalTerms=true&locationPromptShown=true&showPassword=true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 278, in login
    response = self.sso_rest_client.post(
  File "/usr/local/lib/python3.9/site-packages/garminconnect/__init__.py", line 96, in post
    raise GarminConnectConnectionError(f"Forbidden url: {url}") from err
garminconnect.GarminConnectConnectionError: Forbidden url: https://sso.garmin.com/sso/signin`

I've verified my credentials by logging directly into https://connect.garmin.com/ .

**Comment by theflyingwombat** [comment]
I have been playing around with this and I have been able to successfully sign in if I edit the User_Agent header to random parameters using the fake_useragent python module.  It also appears to require the origin header as well.

`
from fake_useragent import UserAgent

ua = UserAgent()
random_ua = ua.random

default_headers = {
        "User-Agent": random_ua,
        "origin': 'https://sso.garmin.com'}
`

**Comment by cyberjunky** [comment]
@theflyingwombat nice! Will implement it asap... thanks!

**Comment by theflyingwombat** [comment]
@cyberjunky  I still get a few 403 forbidden but it is significantly less than it used to be.

**Comment by julianlatasa** [comment]
@cyberjunky I use to have the same problem, changin the login, and saving and restoring session, solved the problem almost all the time. If you want, I can make a pull request with the changes to implement session saving and restore.

**Comment by cyberjunky** [comment]
@julianlatasa I'm open for a Pull Request for sure! Because I'm a bit short on development time, this would be great!
