### ISSUE TITLE
Self Evaluation data

### ISSUE THREAD

**Issue by dpupkov** [cyberjunky/python-garminconnect#64]
Is it possible to get "Self Evaluation" datafields with either get_activities() or get_activity_details()? Pretty sure data should be somewhere, but can't find any clues in my activities :(

**Comment by dpupkov** [comment]
Got the Self Evaluation data directly from the .fit files. But it would have been easier to get Self Evaluation data via separate _garminconnect_ request like we have for weather data.

**Comment by dpupkov** [comment]
Data can be retrieved with the following request https://connect.garmin.com/modern/proxy/activity-service/activity/{activity_id} and it is stored in two fields in summaryDTO:

"directWorkoutFeel":75
"directWorkoutRpe":50

From my understanding, these fields are not returned neither via get_activities(), nor via get_activity_details().

**Comment by cyberjunky** [comment]
Hi thanks alot!

I have added get_activity_evaluation to version 0.1.43

The output contains the summaryDTO section, could not see the directWorkout values, but maybe that depends on activity type and/or user response.

Can you test?

```
   # Get activities data from start and limit
    activities = api.get_activities(0,10) # 0=start, 10=limit

    ## Activity self evaluation data
    for activity in activities:
        activity_id = activity["activityId"]
        logger.info(api.get_activity_evaluation(activity_id))
```
