### ISSUE TITLE
get_activities_by_date removed

### ISSUE THREAD

**Issue by hannesweisbach** [cyberjunky/python-garminconnect#67]
Hi,

I recently upgraded from 0.1.23 to 0.1.43 and noticed get_activities_by_date() was removed by b0c56345d2eb82e4.

Since I need that functionalty I was going to re-implement it either in my code or python-garminconnect. Is there interest in merging that functionality in python-garminconnect if I opened a PR?

Best regards,
Hannes

**Comment by cyberjunky** [comment]
Yes, it was not done on purpose, so PR is welcome, sorry :wink:

**Comment by cyberjunky** [comment]
I just put package 0.1.44 online on pypi, will be visible is a few minutes.
