### ISSUE TITLE
Garmin.fetch_data: TypeError Garmin.login() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by njkalish** [cyberjunky/python-garminconnect#7]
https://github.com/cyberjunky/python-garminconnect/blob/3fcdf55405b6fa23e6ecb1e55fa18afabb4b20f5/garminconnect/__init__.py#L143

Garmin.login(self) does not take any arguments, but is called with self.email and self.password

**Comment by cyberjunky** [comment]
Good catch, will correct it, thanks!

**Comment by cyberjunky** [comment]
Fixed in latest version 0.1.12 on PyPi and master in github, I just saw that the version/tags didn't match, but 0.1.12 is official latest version.
