### ISSUE TITLE
Pulling strength training activities with each set's weight rather than volume?

### ISSUE THREAD

**Issue by geodesicPenguin** [cyberjunky/python-garminconnect#70]
The data in a strength training activity gives the specific exercise, reps and sets, but it doesn't give weight. The integer given for "volume" is the next best thing but seems to be a summation of the weight for all sets. Is there a way to get the activity data to give weight for all sets? Thanks.

**Comment by dpupkov** [comment]
Probably easiest way would be to download complete .fit file and parse it?

**Comment by lfcipriani** [comment]
I created a [PR](https://github.com/cyberjunky/python-garminconnect/pull/107) that enables fecthing exercise sets out of strength trainings.
