### ISSUE TITLE
Question - how do I get my goals

### ISSUE THREAD

**Issue by johnnychicago** [cyberjunky/python-garminconnect#79]
Hello --
My apologies, I am not smart around this. I usually manage to grep, awk and sed my way through to get a datapoint out of a scraped webpage or similar.
I installed and ran the test program just fine. What I am after is the contents of my goals, as on https://connect.garmin.com/modern/goals. I've been trying different variations of calls to get them, but no luck.
Anybody care to give a hint, please?
Many thanks :)

**Comment by cyberjunky** [comment]
I haven't found a working API call yet.

**Comment by dpfrakes** [comment]
I took a stab at this, seems to be working for me :grin:  https://github.com/cyberjunky/python-garminconnect/pull/97

**Comment by cyberjunky** [comment]
@johnnychicago thanks to @dpfrakes this is now included in version 0.1.49!
