### ISSUE TITLE
Body data format problem

### ISSUE THREAD

**Issue by PavelHonza** [cyberjunky/python-garminconnect#8]
Problem to parse "body data" from Garmin connect - example of Garmin data format 

`{ 
"startDate": "2020-04-21", 
"endDate": "2020-04-22",
 "dateWeightList": 
     
       [ { "samplePk": 1587514937000, "date": 1587522137000, "calendarDate": "2020-04-22", "weight": 88849.9984741211, "bmi": 26.799999237060547, "bodyFat": 15.289999961853027, "bodyWater": 61.83000183105469, "boneMass": 6639, "muscleMass": 36130, "physiqueRating": null, "visceralFat": null, "metabolicAge": null, "sourceType": "INDEX_SCALE", "timestampGMT": 1587514937000, "weightDelta": 2299.9999999999973 } 
       ], 

"totalAverage": { "from": 1587427200000, "until": 1587599999999, "weight": 88849.9984741211, "bmi": 26.799999237060547, "bodyFat": 15.289999961853027, "bodyWater": 61.83000183105469, "boneMass": 6639, "muscleMass": 36130, "physiqueRating": null, "visceralFat": null, "metabolicAge": null, "weightCount": 1, "bmiCount": 1, "bodyFatCount": 1, "bodyWaterCount": 1, "boneMassCount": 1, "muscleMassCount": 1, "physiqueRatingCount": 0, "visceralFatCount": 0, "metabolicAgeCount": 0 } }
`

**Comment by cyberjunky** [comment]
@PavelHonza can you try last version and if it doesn't work give more information how you call it and what is missing?

**Comment by cyberjunky** [comment]
Closed for now, if you still have this issue let us know.

**Comment by PavelHonza** [comment]
Sorry CJ, now I see that this is wrong project. I wanted to report homeassistant bug with garmin connect.

**Comment by cyberjunky** [comment]
Ah oke, that one is fixed in latest version 0.111.0

Op ma 8 jun. 2020 16:41 schreef Honza Pavel <notifications@github.com>:
