### ISSUE TITLE
Upload activity

### ISSUE THREAD

**Issue by hishizuka** [cyberjunky/python-garminconnect#88]
Hi, your project is so nice that it can authenticates reliably. Many other projects cannot.

I need the activity upload function. After many attempts, I found the workaround code.
```
additional_url = "proxy/upload-service/upload/.fit"
fit_file = "some_actifity.fit"
with open(fit_file, 'rb') as file:
    res = api.modern_rest_client.post(additional_url, {}, {}, file)
```
Can you implement above as an official function?

Thanks

**Comment by cyberjunky** [comment]
Any idea where I can get an example fit file to test with?

**Comment by hishizuka** [comment]
Thanks for your reply! 

Assume you have a Garmin Connect account and have some activities.

1. Open one of your activity and export the original from the settings in the upper right corner. This zip file conatinis the FIT file.
<img width="314" alt="スクリーンショット 2022-10-21 10 36 40" src="https://user-images.githubusercontent.com/12926652/197091193-d7356e0d-0a5a-430f-ba11-420698d034c2.png">

2. Delete this activity. If same activity already exists, your code returns 409 Client Error。
3. Upload this FIT file with the workaround.

**Comment by cyberjunky** [comment]
Hi @hishizuka Thank you, I have added it to Release 0.1.46, the call is called 'api.upload_fit_activity(activityfitfile)' you can find it in the example program as well.

**Comment by hishizuka** [comment]
Thanks so much!
I'll get it into my program "pizero_bikecomputer".

**Comment by cyberjunky** [comment]
@hishizuka I have just replaced it in version 0.1.48 with the more generic api.upload_activity(file) which supports multiple filetypes.

**Comment by cyberjunky** [comment]
@hishizuka I have come across your project earlier, not knowing you use my code, very nice!!
