### ISSUE TITLE
Can I get my shoes information as stored in Stryd with garminconnect?

### ISSUE THREAD

**Issue by peewel** [cyberjunky/python-garminconnect#90]
I download a lot of data collected with my Stryd app using this garmin connect API. It works very nice! 
But I am about to change my shoes. In the Stryd app, the mileage as run with my shoes are stored.
My question: is the shoes identifier as listed in Stryd also available to download using Garmin Connect?

**Comment by cyberjunky** [comment]
What does a shoes identifier look like? You ask because it is missing from the shoe information you Download from Garmin Connect? Is it visible somewhere in the Garmin app or Garmin Connect web site?
