### ISSUE TITLE
HRV data during night

### ISSUE THREAD

**Issue by dpupkov** [cyberjunky/python-garminconnect#93]
Kindly please add HRV readings during night, here is the point https://connect.garmin.com/hrv-service/hrv/2022-10-05

And data example:

`{"userProfilePk":4118282,"hrvSummary":{"calendarDate":"2022-10-05","weeklyAvg":57,"lastNightAvg":56,"lastNight5MinHigh":92,"baseline":{"lowUpper":45,"balancedLow":48,"balancedUpper":62,"markerValue":0.5714264},"status":"BALANCED","feedbackPhrase":"HRV_BALANCED_7","createTimeStamp":"2022-10-04T21:15:45.564"},"hrvReadings":[{"hrvValue":40,"readingTimeGMT":"2022-10-04T12:13:52.0","readingTimeLocal":"2022-10-04T23:13:52.0"},{"hrvValue":38,"readingTimeGMT":"2022-10-04T12:18:52.0","readingTimeLocal":"2022-10-04T23:18:52.0"},{"hrvValue":41,"readingTimeGMT":"2022-10-04T12:23:52.0","readingTimeLocal":"2022-10-04T23:23:52.0"},{"hrvValue":34,"readingTimeGMT":"2022-10-04T12:28:52.0","readingTimeLocal":"2022-10-04T23:28:52.0"},{"hrvValue":32,"readingTimeGMT":"2022-10-04T12:33:52.0","readingTimeLocal":"2022-10-04T23:33:52.0"},{"hrvValue":32,"readingTimeGMT":"2022-10-04T12:38:52.0","readingTimeLocal":"2022-10-04T23:38:52.0"},{"hrvValue":35,"readingTimeGMT":"2022-10-04T12:43:52.0","readingTimeLocal":"2022-10-04T23:43:52.0"},{"hrvValue":35,"readingTimeGMT":"2022-10-04T12:48:52.0","readingTimeLocal":"2022-10-04T23:48:52.0"},{"hrvValue":34,"readingTimeGMT":"2022-10-04T12:53:52.0","readingTimeLocal":"2022-10-04T23:53:52.0"},{"hrvValue":42,"readingTimeGMT":"2022-10-04T12:58:52.0","readingTimeLocal":"2022-10-04T23:58:52.0"},{"hrvValue":45,"readingTimeGMT":"2022-10-04T13:03:52.0","readingTimeLocal":"2022-10-05T00:03:52.0"},{"hrvValue":44,"readingTimeGMT":"2022-10-04T13:08:52.0","readingTimeLocal":"2022-10-05T00:08:52.0"},{"hrvValue":48,"readingTimeGMT":"2022-10-04T13:13:52.0","readingTimeLocal":"2022-10-05T00:13:52.0"},{"hrvValue":47,"readingTimeGMT":"2022-10-04T13:18:52.0","readingTimeLocal":"2022-10-05T00:18:52.0"},{"hrvValue":55,"readingTimeGMT":"2022-10-04T13:23:52.0","readingTimeLocal":"2022-10-05T00:23:52.0"},{"hrvValue":57,"readingTimeGMT":"2022-10-04T13:28:52.0","readingTimeLocal":"2022-10-05T00:28:52.0"},{"hrvValue":46,"readingTimeGMT":"2022-10-04T13:33:52.0","readingTimeLocal":"2022-10-05T00:33:52.0"},{"hrvValue":46,"readingTimeGMT":"2022-10-04T13:38:52.0","readingTimeLocal":"2022-10-05T00:38:52.0"},{"hrvValue":46,"readingTimeGMT":"2022-10-04T13:43:52.0","readingTimeLocal":"2022-10-05T00:43:52.0"},{"hrvValue":44,"readingTimeGMT":"2022-10-04T13:48:52.0","readingTimeLocal":"2022-10-05T00:48:52.0"},{"hrvValue":51,"readingTimeGMT":"2022-10-04T13:53:52.0","readingTimeLocal":"2022-10-05T00:53:52.0"},{"hrvValue":48,"readingTimeGMT":"2022-10-04T13:58:52.0","readingTimeLocal":"2022-10-05T00:58:52.0"},{"hrvValue":51,"readingTimeGMT":"2022-10-04T14:03:52.0","readingTimeLocal":"2022-10-05T01:03:52.0"},{"hrvValue":51,"readingTimeGMT":"2022-10-04T14:08:52.0","readingTimeLocal":"2022-10-05T01:08:52.0"},{"hrvValue":61,"readingTimeGMT":"2022-10-04T14:13:52.0","readingTimeLocal":"2022-10-05T01:13:52.0"},{"hrvValue":57,"readingTimeGMT":"2022-10-04T14:18:52.0","readingTimeLocal":"2022-10-05T01:18:52.0"},{"hrvValue":68,"readingTimeGMT":"2022-10-04T14:23:52.0","readingTimeLocal":"2022-10-05T01:23:52.0"},{"hrvValue":77,"readingTimeGMT":"2022-10-04T14:28:52.0","readingTimeLocal":"2022-10-05T01:28:52.0"},{"hrvValue":61,"readingTimeGMT":"2022-10-04T14:33:52.0","readingTimeLocal":"2022-10-05T01:33:52.0"},{"hrvValue":58,"readingTimeGMT":"2022-10-04T14:38:52.0","readingTimeLocal":"2022-10-05T01:38:52.0"},{"hrvValue":76,"readingTimeGMT":"2022-10-04T14:43:52.0","readingTimeLocal":"2022-10-05T01:43:52.0"},{"hrvValue":80,"readingTimeGMT":"2022-10-04T14:48:52.0","readingTimeLocal":"2022-10-05T01:48:52.0"},{"hrvValue":61,"readingTimeGMT":"2022-10-04T14:53:52.0","readingTimeLocal":"2022-10-05T01:53:52.0"},{"hrvValue":53,"readingTimeGMT":"2022-10-04T14:58:52.0","readingTimeLocal":"2022-10-05T01:58:52.0"},{"hrvValue":63,"readingTimeGMT":"2022-10-04T15:03:52.0","readingTimeLocal":"2022-10-05T02:03:52.0"},{"hrvValue":46,"readingTimeGMT":"2022-10-04T15:08:52.0","readingTimeLocal":"2022-10-05T02:08:52.0"},{"hrvValue":52,"readingTimeGMT":"2022-10-04T15:13:52.0","readingTimeLocal":"2022-10-05T02:13:52.0"},{"hrvValue":44,"readingTimeGMT":"2022-10-04T15:18:52.0","readingTimeLocal":"2022-10-05T02:18:52.0"},{"hrvValue":45,"readingTimeGMT":"2022-10-04T15:23:52.0","readingTimeLocal":"2022-10-05T02:23:52.0"},{"hrvValue":39,"readingTimeGMT":"2022-10-04T15:28:52.0","readingTimeLocal":"2022-10-05T02:28:52.0"},{"hrvValue":41,"readingTimeGMT":"2022-10-04T15:33:52.0","readingTimeLocal":"2022-10-05T02:33:52.0"},{"hrvValue":42,"readingTimeGMT":"2022-10-04T15:38:52.0","readingTimeLocal":"2022-10-05T02:38:52.0"},{"hrvValue":62,"readingTimeGMT":"2022-10-04T15:43:52.0","readingTimeLocal":"2022-10-05T02:43:52.0"},{"hrvValue":39,"readingTimeGMT":"2022-10-04T15:48:52.0","readingTimeLocal":"2022-10-05T02:48:52.0"},{"hrvValue":47,"readingTimeGMT":"2022-10-04T15:53:52.0","readingTimeLocal":"2022-10-05T02:53:52.0"},{"hrvValue":54,"readingTimeGMT":"2022-10-04T15:58:52.0","readingTimeLocal":"2022-10-05T02:58:52.0"},{"hrvValue":61,"readingTimeGMT":"2022-10-04T16:03:52.0","readingTimeLocal":"2022-10-05T03:03:52.0"},{"hrvValue":62,"readingTimeGMT":"2022-10-04T16:08:52.0","readingTimeLocal":"2022-10-05T03:08:52.0"},{"hrvValue":69,"readingTimeGMT":"2022-10-04T16:13:52.0","readingTimeLocal":"2022-10-05T03:13:52.0"},{"hrvValue":49,"readingTimeGMT":"2022-10-04T16:18:52.0","readingTimeLocal":"2022-10-05T03:18:52.0"},{"hrvValue":53,"readingTimeGMT":"2022-10-04T16:23:52.0","readingTimeLocal":"2022-10-05T03:23:52.0"},{"hrvValue":49,"readingTimeGMT":"2022-10-04T16:28:52.0","readingTimeLocal":"2022-10-05T03:28:52.0"},{"hrvValue":66,"readingTimeGMT":"2022-10-04T16:33:52.0","readingTimeLocal":"2022-10-05T03:33:52.0"},{"hrvValue":83,"readingTimeGMT":"2022-10-04T16:38:52.0","readingTimeLocal":"2022-10-05T03:38:52.0"},{"hrvValue":92,"readingTimeGMT":"2022-10-04T16:43:52.0","readingTimeLocal":"2022-10-05T03:43:52.0"},{"hrvValue":69,"readingTimeGMT":"2022-10-04T16:48:52.0","readingTimeLocal":"2022-10-05T03:48:52.0"},{"hrvValue":65,"readingTimeGMT":"2022-10-04T16:53:52.0","readingTimeLocal":"2022-10-05T03:53:52.0"},{"hrvValue":69,"readingTimeGMT":"2022-10-04T16:58:52.0","readingTimeLocal":"2022-10-05T03:58:52.0"},{"hrvValue":63,"readingTimeGMT":"2022-10-04T17:03:52.0","readingTimeLocal":"2022-10-05T04:03:52.0"},{"hrvValue":52,"readingTimeGMT":"2022-10-04T17:08:52.0","readingTimeLocal":"2022-10-05T04:08:52.0"},{"hrvValue":51,"readingTimeGMT":"2022-10-04T17:13:52.0","readingTimeLocal":"2022-10-05T04:13:52.0"},{"hrvValue":49,"readingTimeGMT":"2022-10-04T17:18:52.0","readingTimeLocal":"2022-10-05T04:18:52.0"},{"hrvValue":46,"readingTimeGMT":"2022-10-04T17:23:52.0","readingTimeLocal":"2022-10-05T04:23:52.0"},{"hrvValue":50,"readingTimeGMT":"2022-10-04T17:28:52.0","readingTimeLocal":"2022-10-05T04:28:52.0"},{"hrvValue":45,"readingTimeGMT":"2022-10-04T17:33:52.0","readingTimeLocal":"2022-10-05T04:33:52.0"},{"hrvValue":45,"readingTimeGMT":"2022-10-04T17:38:52.0","readingTimeLocal":"2022-10-05T04:38:52.0"},{"hrvValue":48,"readingTimeGMT":"2022-10-04T17:43:52.0","readingTimeLocal":"2022-10-05T04:43:52.0"},{"hrvValue":49,"readingTimeGMT":"2022-10-04T17:48:52.0","readingTimeLocal":"2022-10-05T04:48:52.0"},{"hrvValue":53,"readingTimeGMT":"2022-10-04T17:53:52.0","readingTimeLocal":"2022-10-05T04:53:52.0"},{"hrvValue":47,"readingTimeGMT":"2022-10-04T17:58:52.0","readingTimeLocal":"2022-10-05T04:58:52.0"},{"hrvValue":59,"readingTimeGMT":"2022-10-04T18:03:52.0","readingTimeLocal":"2022-10-05T05:03:52.0"},{"hrvValue":63,"readingTimeGMT":"2022-10-04T18:08:52.0","readingTimeLocal":"2022-10-05T05:08:52.0"},{"hrvValue":58,"readingTimeGMT":"2022-10-04T18:13:52.0","readingTimeLocal":"2022-10-05T05:13:52.0"},{"hrvValue":57,"readingTimeGMT":"2022-10-04T18:18:52.0","readingTimeLocal":"2022-10-05T05:18:52.0"},{"hrvValue":69,"readingTimeGMT":"2022-10-04T18:23:52.0","readingTimeLocal":"2022-10-05T05:23:52.0"},{"hrvValue":76,"readingTimeGMT":"2022-10-04T18:28:52.0","readingTimeLocal":"2022-10-05T05:28:52.0"},{"hrvValue":76,"readingTimeGMT":"2022-10-04T18:33:52.0","readingTimeLocal":"2022-10-05T05:33:52.0"},{"hrvValue":74,"readingTimeGMT":"2022-10-04T18:38:52.0","readingTimeLocal":"2022-10-05T05:38:52.0"},{"hrvValue":49,"readingTimeGMT":"2022-10-04T18:43:52.0","readingTimeLocal":"2022-10-05T05:43:52.0"},{"hrvValue":55,"readingTimeGMT":"2022-10-04T18:48:52.0","readingTimeLocal":"2022-10-05T05:48:52.0"},{"hrvValue":46,"readingTimeGMT":"2022-10-04T18:53:52.0","readingTimeLocal":"2022-10-05T05:53:52.0"},{"hrvValue":70,"readingTimeGMT":"2022-10-04T18:58:52.0","readingTimeLocal":"2022-10-05T05:58:52.0"},{"hrvValue":64,"readingTimeGMT":"2022-10-04T19:03:52.0","readingTimeLocal":"2022-10-05T06:03:52.0"},{"hrvValue":71,"readingTimeGMT":"2022-10-04T19:08:52.0","readingTimeLocal":"2022-10-05T06:08:52.0"},{"hrvValue":74,"readingTimeGMT":"2022-10-04T19:13:52.0","readingTimeLocal":"2022-10-05T06:13:52.0"},{"hrvValue":69,"readingTimeGMT":"2022-10-04T19:18:52.0","readingTimeLocal":"2022-10-05T06:18:52.0"},{"hrvValue":65,"readingTimeGMT":"2022-10-04T19:23:52.0","readingTimeLocal":"2022-10-05T06:23:52.0"},{"hrvValue":71,"readingTimeGMT":"2022-10-04T19:28:52.0","readingTimeLocal":"2022-10-05T06:28:52.0"},{"hrvValue":65,"readingTimeGMT":"2022-10-04T19:33:52.0","readingTimeLocal":"2022-10-05T06:33:52.0"},{"hrvValue":65,"readingTimeGMT":"2022-10-04T19:38:52.0","readingTimeLocal":"2022-10-05T06:38:52.0"},{"hrvValue":56,"readingTimeGMT":"2022-10-04T19:43:52.0","readingTimeLocal":"2022-10-05T06:43:52.0"},{"hrvValue":54,"readingTimeGMT":"2022-10-04T19:48:52.0","readingTimeLocal":"2022-10-05T06:48:52.0"},{"hrvValue":59,"readingTimeGMT":"2022-10-04T19:53:52.0","readingTimeLocal":"2022-10-05T06:53:52.0"},{"hrvValue":78,"readingTimeGMT":"2022-10-04T19:58:52.0","readingTimeLocal":"2022-10-05T06:58:52.0"},{"hrvValue":71,"readingTimeGMT":"2022-10-04T20:03:52.0","readingTimeLocal":"2022-10-05T07:03:52.0"},{"hrvValue":63,"readingTimeGMT":"2022-10-04T20:08:52.0","readingTimeLocal":"2022-10-05T07:08:52.0"},{"hrvValue":63,"readingTimeGMT":"2022-10-04T20:13:52.0","readingTimeLocal":"2022-10-05T07:13:52.0"},{"hrvValue":65,"readingTimeGMT":"2022-10-04T20:18:52.0","readingTimeLocal":"2022-10-05T07:18:52.0"},{"hrvValue":52,"readingTimeGMT":"2022-10-04T20:23:52.0","readingTimeLocal":"2022-10-05T07:23:52.0"},{"hrvValue":43,"readingTimeGMT":"2022-10-04T20:28:52.0","readingTimeLocal":"2022-10-05T07:28:52.0"},{"hrvValue":38,"readingTimeGMT":"2022-10-04T20:33:52.0","readingTimeLocal":"2022-10-05T07:33:52.0"},{"hrvValue":53,"readingTimeGMT":"2022-10-04T20:38:52.0","readingTimeLocal":"2022-10-05T07:38:52.0"},{"hrvValue":47,"readingTimeGMT":"2022-10-04T20:43:52.0","readingTimeLocal":"2022-10-05T07:43:52.0"},{"hrvValue":55,"readingTimeGMT":"2022-10-04T20:48:52.0","readingTimeLocal":"2022-10-05T07:48:52.0"},{"hrvValue":59,"readingTimeGMT":"2022-10-04T20:53:52.0","readingTimeLocal":"2022-10-05T07:53:52.0"},{"hrvValue":59,"readingTimeGMT":"2022-10-04T20:58:52.0","readingTimeLocal":"2022-10-05T07:58:52.0"},{"hrvValue":65,"readingTimeGMT":"2022-10-04T21:03:52.0","readingTimeLocal":"2022-10-05T08:03:52.0"}],"startTimestampGMT":"2022-10-04T12:09:00.0","endTimestampGMT":"2022-10-04T21:03:52.0","startTimestampLocal":"2022-10-04T23:09:00.0","endTimestampLocal":"2022-10-05T08:03:52.0","sleepStartTimestampGMT":"2022-10-04T12:09:00.0","sleepEndTimestampGMT":"2022-10-04T21:06:00.0","sleepStartTimestampLocal":"2022-10-04T23:09:00.0","sleepEndTimestampLocal":"2022-10-05T08:06:00.0"}`

**Comment by cyberjunky** [comment]
@dpupkov  Busy implementing this, but unfortunatly the url is not valid for my instance, where did you find it?

**Comment by SteveClement** [comment]
Same here, this end-point does not exist.

**Comment by cyberjunky** [comment]
@dpupkov @SteveClement  have added the call to latest code (not in release)
It's under the 'x' in the example code, the normal .json() call didn't return json if I try it so it returns '.text' for now, can you try and see what it does?

**Comment by cyberjunky** [comment]
I have a simple Vivoactive 4, don't think it's supported..

**Comment by Metzlmane** [comment]
works perfectly, thanks a lot!

**Comment by cyberjunky** [comment]
Closing as it seems fixed!
